/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicCountryDto,
} from '../models/index';
import {
    PublicCountryDtoFromJSON,
    PublicCountryDtoToJSON,
} from '../models/index';

export interface CountryFindDevicesV1Request {
    name?: any;
    xAuthProvider?: string;
    xAuthStrategy?: string;
}

/**
 * CountryApi - interface
 * 
 * @export
 * @interface CountryApiInterface
 */
export interface CountryApiInterface {
    /**
     * 
     * @param {any} [name] 
     * @param {string} [xAuthProvider] 
     * @param {string} [xAuthStrategy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CountryApiInterface
     */
    countryFindDevicesV1Raw(requestParameters: CountryFindDevicesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicCountryDto>>>;

    /**
     */
    countryFindDevicesV1(requestParameters: CountryFindDevicesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicCountryDto>>;

}

/**
 * 
 */
export class CountryApi extends runtime.BaseAPI implements CountryApiInterface {

    /**
     */
    async countryFindDevicesV1Raw(requestParameters: CountryFindDevicesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicCountryDto>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAuthProvider'] != null) {
            headerParameters['x-auth-provider'] = String(requestParameters['xAuthProvider']);
        }

        if (requestParameters['xAuthStrategy'] != null) {
            headerParameters['x-auth-strategy'] = String(requestParameters['xAuthStrategy']);
        }

        const response = await this.request({
            path: `/v1/country`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicCountryDtoFromJSON));
    }

    /**
     */
    async countryFindDevicesV1(requestParameters: CountryFindDevicesV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicCountryDto>> {
        const response = await this.countryFindDevicesV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
