/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicDeviceDto,
} from '../models/index';
import {
    PublicDeviceDtoFromJSON,
    PublicDeviceDtoToJSON,
} from '../models/index';

export interface DeviceFindDevicesV1Request {
    name?: any;
    xAuthProvider?: string;
    xAuthStrategy?: string;
}

/**
 * DeviceApi - interface
 * 
 * @export
 * @interface DeviceApiInterface
 */
export interface DeviceApiInterface {
    /**
     * 
     * @param {any} [name] 
     * @param {string} [xAuthProvider] 
     * @param {string} [xAuthStrategy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceApiInterface
     */
    deviceFindDevicesV1Raw(requestParameters: DeviceFindDevicesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicDeviceDto>>>;

    /**
     */
    deviceFindDevicesV1(requestParameters: DeviceFindDevicesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicDeviceDto>>;

}

/**
 * 
 */
export class DeviceApi extends runtime.BaseAPI implements DeviceApiInterface {

    /**
     */
    async deviceFindDevicesV1Raw(requestParameters: DeviceFindDevicesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicDeviceDto>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAuthProvider'] != null) {
            headerParameters['x-auth-provider'] = String(requestParameters['xAuthProvider']);
        }

        if (requestParameters['xAuthStrategy'] != null) {
            headerParameters['x-auth-strategy'] = String(requestParameters['xAuthStrategy']);
        }

        const response = await this.request({
            path: `/v1/device`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicDeviceDtoFromJSON));
    }

    /**
     */
    async deviceFindDevicesV1(requestParameters: DeviceFindDevicesV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicDeviceDto>> {
        const response = await this.deviceFindDevicesV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
