/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthCheckV1200Response,
  HealthCheckV1503Response,
} from '../models/index';
import {
    HealthCheckV1200ResponseFromJSON,
    HealthCheckV1200ResponseToJSON,
    HealthCheckV1503ResponseFromJSON,
    HealthCheckV1503ResponseToJSON,
} from '../models/index';

export interface HealthCheckV1Request {
    xAuthProvider?: string;
    xAuthStrategy?: string;
}

/**
 * HealthApi - interface
 * 
 * @export
 * @interface HealthApiInterface
 */
export interface HealthApiInterface {
    /**
     * 
     * @param {string} [xAuthProvider] 
     * @param {string} [xAuthStrategy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthCheckV1Raw(requestParameters: HealthCheckV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthCheckV1200Response>>;

    /**
     */
    healthCheckV1(requestParameters: HealthCheckV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthCheckV1200Response>;

}

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI implements HealthApiInterface {

    /**
     */
    async healthCheckV1Raw(requestParameters: HealthCheckV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthCheckV1200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAuthProvider'] != null) {
            headerParameters['x-auth-provider'] = String(requestParameters['xAuthProvider']);
        }

        if (requestParameters['xAuthStrategy'] != null) {
            headerParameters['x-auth-strategy'] = String(requestParameters['xAuthStrategy']);
        }

        const response = await this.request({
            path: `/v1/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckV1200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async healthCheckV1(requestParameters: HealthCheckV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthCheckV1200Response> {
        const response = await this.healthCheckV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
