/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicOfferWithPlanWithVolumesDto,
} from '../models/index';
import {
    PublicOfferWithPlanWithVolumesDtoFromJSON,
    PublicOfferWithPlanWithVolumesDtoToJSON,
} from '../models/index';

export interface OfferFindAllPublicValidV1Request {
    xAuthProvider?: string;
    xAuthStrategy?: string;
}

/**
 * OfferApi - interface
 * 
 * @export
 * @interface OfferApiInterface
 */
export interface OfferApiInterface {
    /**
     * 
     * @param {string} [xAuthProvider] 
     * @param {string} [xAuthStrategy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfferApiInterface
     */
    offerFindAllPublicValidV1Raw(requestParameters: OfferFindAllPublicValidV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicOfferWithPlanWithVolumesDto>>>;

    /**
     */
    offerFindAllPublicValidV1(requestParameters: OfferFindAllPublicValidV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicOfferWithPlanWithVolumesDto>>;

}

/**
 * 
 */
export class OfferApi extends runtime.BaseAPI implements OfferApiInterface {

    /**
     */
    async offerFindAllPublicValidV1Raw(requestParameters: OfferFindAllPublicValidV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicOfferWithPlanWithVolumesDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAuthProvider'] != null) {
            headerParameters['x-auth-provider'] = String(requestParameters['xAuthProvider']);
        }

        if (requestParameters['xAuthStrategy'] != null) {
            headerParameters['x-auth-strategy'] = String(requestParameters['xAuthStrategy']);
        }

        const response = await this.request({
            path: `/v1/offer/public`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicOfferWithPlanWithVolumesDtoFromJSON));
    }

    /**
     */
    async offerFindAllPublicValidV1(requestParameters: OfferFindAllPublicValidV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicOfferWithPlanWithVolumesDto>> {
        const response = await this.offerFindAllPublicValidV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
