/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicOnboardingStageDto,
} from '../models/index';
import {
    PublicOnboardingStageDtoFromJSON,
    PublicOnboardingStageDtoToJSON,
} from '../models/index';

export interface OnboardingFindAllPublicStagesV1Request {
    xAuthProvider?: string;
    xAuthStrategy?: string;
}

/**
 * OnboardingApi - interface
 * 
 * @export
 * @interface OnboardingApiInterface
 */
export interface OnboardingApiInterface {
    /**
     * 
     * @param {string} [xAuthProvider] 
     * @param {string} [xAuthStrategy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnboardingApiInterface
     */
    onboardingFindAllPublicStagesV1Raw(requestParameters: OnboardingFindAllPublicStagesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicOnboardingStageDto>>>;

    /**
     */
    onboardingFindAllPublicStagesV1(requestParameters: OnboardingFindAllPublicStagesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicOnboardingStageDto>>;

}

/**
 * 
 */
export class OnboardingApi extends runtime.BaseAPI implements OnboardingApiInterface {

    /**
     */
    async onboardingFindAllPublicStagesV1Raw(requestParameters: OnboardingFindAllPublicStagesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicOnboardingStageDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAuthProvider'] != null) {
            headerParameters['x-auth-provider'] = String(requestParameters['xAuthProvider']);
        }

        if (requestParameters['xAuthStrategy'] != null) {
            headerParameters['x-auth-strategy'] = String(requestParameters['xAuthStrategy']);
        }

        const response = await this.request({
            path: `/v1/onboarding/public`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicOnboardingStageDtoFromJSON));
    }

    /**
     */
    async onboardingFindAllPublicStagesV1(requestParameters: OnboardingFindAllPublicStagesV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicOnboardingStageDto>> {
        const response = await this.onboardingFindAllPublicStagesV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
