/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicPromoCodeWithOffersDto,
} from '../models/index';
import {
    PublicPromoCodeWithOffersDtoFromJSON,
    PublicPromoCodeWithOffersDtoToJSON,
} from '../models/index';

export interface PromoCodeFindByCodeV1Request {
    code: string;
    xAuthProvider?: string;
    xAuthStrategy?: string;
}

/**
 * PromoCodeApi - interface
 * 
 * @export
 * @interface PromoCodeApiInterface
 */
export interface PromoCodeApiInterface {
    /**
     * 
     * @param {string} code 
     * @param {string} [xAuthProvider] 
     * @param {string} [xAuthStrategy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodeApiInterface
     */
    promoCodeFindByCodeV1Raw(requestParameters: PromoCodeFindByCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicPromoCodeWithOffersDto>>;

    /**
     */
    promoCodeFindByCodeV1(requestParameters: PromoCodeFindByCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicPromoCodeWithOffersDto>;

}

/**
 * 
 */
export class PromoCodeApi extends runtime.BaseAPI implements PromoCodeApiInterface {

    /**
     */
    async promoCodeFindByCodeV1Raw(requestParameters: PromoCodeFindByCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicPromoCodeWithOffersDto>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling promoCodeFindByCodeV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAuthProvider'] != null) {
            headerParameters['x-auth-provider'] = String(requestParameters['xAuthProvider']);
        }

        if (requestParameters['xAuthStrategy'] != null) {
            headerParameters['x-auth-strategy'] = String(requestParameters['xAuthStrategy']);
        }

        const response = await this.request({
            path: `/v1/promo-codes/by-code/{code}`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicPromoCodeWithOffersDtoFromJSON(jsonValue));
    }

    /**
     */
    async promoCodeFindByCodeV1(requestParameters: PromoCodeFindByCodeV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicPromoCodeWithOffersDto> {
        const response = await this.promoCodeFindByCodeV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
