/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicSessionTokensDto,
} from '../models/index';
import {
    PublicSessionTokensDtoFromJSON,
    PublicSessionTokensDtoToJSON,
} from '../models/index';

export interface SessionRefreshSessionV1Request {
    xAuthProvider?: string;
    xAuthStrategy?: string;
}

/**
 * SessionApi - interface
 * 
 * @export
 * @interface SessionApiInterface
 */
export interface SessionApiInterface {
    /**
     * 
     * @param {string} [xAuthProvider] 
     * @param {string} [xAuthStrategy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionApiInterface
     */
    sessionRefreshSessionV1Raw(requestParameters: SessionRefreshSessionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicSessionTokensDto>>;

    /**
     */
    sessionRefreshSessionV1(requestParameters: SessionRefreshSessionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicSessionTokensDto>;

}

/**
 * 
 */
export class SessionApi extends runtime.BaseAPI implements SessionApiInterface {

    /**
     */
    async sessionRefreshSessionV1Raw(requestParameters: SessionRefreshSessionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicSessionTokensDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAuthProvider'] != null) {
            headerParameters['x-auth-provider'] = String(requestParameters['xAuthProvider']);
        }

        if (requestParameters['xAuthStrategy'] != null) {
            headerParameters['x-auth-strategy'] = String(requestParameters['xAuthStrategy']);
        }

        const response = await this.request({
            path: `/v1/sessions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicSessionTokensDtoFromJSON(jsonValue));
    }

    /**
     */
    async sessionRefreshSessionV1(requestParameters: SessionRefreshSessionV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicSessionTokensDto> {
        const response = await this.sessionRefreshSessionV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
