/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthGoogleExchangeCallbackDto
 */
export interface AuthGoogleExchangeCallbackDto {
    /**
     * 
     * @type {string}
     * @memberof AuthGoogleExchangeCallbackDto
     */
    idToken: string;
}

/**
 * Check if a given object implements the AuthGoogleExchangeCallbackDto interface.
 */
export function instanceOfAuthGoogleExchangeCallbackDto(value: object): value is AuthGoogleExchangeCallbackDto {
    if (!('idToken' in value) || value['idToken'] === undefined) return false;
    return true;
}

export function AuthGoogleExchangeCallbackDtoFromJSON(json: any): AuthGoogleExchangeCallbackDto {
    return AuthGoogleExchangeCallbackDtoFromJSONTyped(json, false);
}

export function AuthGoogleExchangeCallbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthGoogleExchangeCallbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'idToken': json['idToken'],
    };
}

export function AuthGoogleExchangeCallbackDtoToJSON(json: any): AuthGoogleExchangeCallbackDto {
    return AuthGoogleExchangeCallbackDtoToJSONTyped(json, false);
}

export function AuthGoogleExchangeCallbackDtoToJSONTyped(value?: AuthGoogleExchangeCallbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idToken': value['idToken'],
    };
}

