/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthAppleLoginRedeemDto
 */
export interface AuthAppleLoginRedeemDto {
    /**
     * 
     * @type {string}
     * @memberof AuthAppleLoginRedeemDto
     */
    code: string;
}

/**
 * Check if a given object implements the AuthAppleLoginRedeemDto interface.
 */
export function instanceOfAuthAppleLoginRedeemDto(value: object): value is AuthAppleLoginRedeemDto {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AuthAppleLoginRedeemDtoFromJSON(json: any): AuthAppleLoginRedeemDto {
    return AuthAppleLoginRedeemDtoFromJSONTyped(json, false);
}

export function AuthAppleLoginRedeemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAppleLoginRedeemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function AuthAppleLoginRedeemDtoToJSON(json: any): AuthAppleLoginRedeemDto {
    return AuthAppleLoginRedeemDtoToJSONTyped(json, false);
}

export function AuthAppleLoginRedeemDtoToJSONTyped(value?: AuthAppleLoginRedeemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

