/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthGoogleLoginRedeemDto
 */
export interface AuthGoogleLoginRedeemDto {
    /**
     * 
     * @type {string}
     * @memberof AuthGoogleLoginRedeemDto
     */
    code: string;
}

/**
 * Check if a given object implements the AuthGoogleLoginRedeemDto interface.
 */
export function instanceOfAuthGoogleLoginRedeemDto(value: object): value is AuthGoogleLoginRedeemDto {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AuthGoogleLoginRedeemDtoFromJSON(json: any): AuthGoogleLoginRedeemDto {
    return AuthGoogleLoginRedeemDtoFromJSONTyped(json, false);
}

export function AuthGoogleLoginRedeemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthGoogleLoginRedeemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function AuthGoogleLoginRedeemDtoToJSON(json: any): AuthGoogleLoginRedeemDto {
    return AuthGoogleLoginRedeemDtoToJSONTyped(json, false);
}

export function AuthGoogleLoginRedeemDtoToJSONTyped(value?: AuthGoogleLoginRedeemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

