/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthAppleExchangeCallbackDto
 */
export interface AuthAppleExchangeCallbackDto {
    /**
     * 
     * @type {string}
     * @memberof AuthAppleExchangeCallbackDto
     */
    idToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAppleExchangeCallbackDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAppleExchangeCallbackDto
     */
    lastName?: string;
}

/**
 * Check if a given object implements the AuthAppleExchangeCallbackDto interface.
 */
export function instanceOfAuthAppleExchangeCallbackDto(value: object): value is AuthAppleExchangeCallbackDto {
    if (!('idToken' in value) || value['idToken'] === undefined) return false;
    return true;
}

export function AuthAppleExchangeCallbackDtoFromJSON(json: any): AuthAppleExchangeCallbackDto {
    return AuthAppleExchangeCallbackDtoFromJSONTyped(json, false);
}

export function AuthAppleExchangeCallbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAppleExchangeCallbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'idToken': json['idToken'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function AuthAppleExchangeCallbackDtoToJSON(json: any): AuthAppleExchangeCallbackDto {
    return AuthAppleExchangeCallbackDtoToJSONTyped(json, false);
}

export function AuthAppleExchangeCallbackDtoToJSONTyped(value?: AuthAppleExchangeCallbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idToken': value['idToken'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

