/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AuthProvider = {
    Local: 'local',
    Google: 'google',
    Apple: 'apple',
    OpenId: 'open-id'
} as const;
export type AuthProvider = typeof AuthProvider[keyof typeof AuthProvider];


export function instanceOfAuthProvider(value: any): boolean {
    for (const key in AuthProvider) {
        if (Object.prototype.hasOwnProperty.call(AuthProvider, key)) {
            if (AuthProvider[key as keyof typeof AuthProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuthProviderFromJSON(json: any): AuthProvider {
    return AuthProviderFromJSONTyped(json, false);
}

export function AuthProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthProvider {
    return json as AuthProvider;
}

export function AuthProviderToJSON(value?: AuthProvider | null): any {
    return value as any;
}

export function AuthProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): AuthProvider {
    return value as AuthProvider;
}

