/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthOpenIdLoginRedeemDto
 */
export interface AuthOpenIdLoginRedeemDto {
    /**
     * 
     * @type {string}
     * @memberof AuthOpenIdLoginRedeemDto
     */
    code: string;
}

/**
 * Check if a given object implements the AuthOpenIdLoginRedeemDto interface.
 */
export function instanceOfAuthOpenIdLoginRedeemDto(value: object): value is AuthOpenIdLoginRedeemDto {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AuthOpenIdLoginRedeemDtoFromJSON(json: any): AuthOpenIdLoginRedeemDto {
    return AuthOpenIdLoginRedeemDtoFromJSONTyped(json, false);
}

export function AuthOpenIdLoginRedeemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthOpenIdLoginRedeemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function AuthOpenIdLoginRedeemDtoToJSON(json: any): AuthOpenIdLoginRedeemDto {
    return AuthOpenIdLoginRedeemDtoToJSONTyped(json, false);
}

export function AuthOpenIdLoginRedeemDtoToJSONTyped(value?: AuthOpenIdLoginRedeemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

