/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthOpenIdExchangeCallbackDto
 */
export interface AuthOpenIdExchangeCallbackDto {
    /**
     * 
     * @type {string}
     * @memberof AuthOpenIdExchangeCallbackDto
     */
    idToken: string;
}

/**
 * Check if a given object implements the AuthOpenIdExchangeCallbackDto interface.
 */
export function instanceOfAuthOpenIdExchangeCallbackDto(value: object): value is AuthOpenIdExchangeCallbackDto {
    if (!('idToken' in value) || value['idToken'] === undefined) return false;
    return true;
}

export function AuthOpenIdExchangeCallbackDtoFromJSON(json: any): AuthOpenIdExchangeCallbackDto {
    return AuthOpenIdExchangeCallbackDtoFromJSONTyped(json, false);
}

export function AuthOpenIdExchangeCallbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthOpenIdExchangeCallbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'idToken': json['idToken'],
    };
}

export function AuthOpenIdExchangeCallbackDtoToJSON(json: any): AuthOpenIdExchangeCallbackDto {
    return AuthOpenIdExchangeCallbackDtoToJSONTyped(json, false);
}

export function AuthOpenIdExchangeCallbackDtoToJSONTyped(value?: AuthOpenIdExchangeCallbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idToken': value['idToken'],
    };
}

