/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeUnverifiedEmailDto
 */
export interface ChangeUnverifiedEmailDto {
    /**
     * 
     * @type {string}
     * @memberof ChangeUnverifiedEmailDto
     */
    oldEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeUnverifiedEmailDto
     */
    newEmail: string;
}

/**
 * Check if a given object implements the ChangeUnverifiedEmailDto interface.
 */
export function instanceOfChangeUnverifiedEmailDto(value: object): value is ChangeUnverifiedEmailDto {
    if (!('oldEmail' in value) || value['oldEmail'] === undefined) return false;
    if (!('newEmail' in value) || value['newEmail'] === undefined) return false;
    return true;
}

export function ChangeUnverifiedEmailDtoFromJSON(json: any): ChangeUnverifiedEmailDto {
    return ChangeUnverifiedEmailDtoFromJSONTyped(json, false);
}

export function ChangeUnverifiedEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUnverifiedEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'oldEmail': json['oldEmail'],
        'newEmail': json['newEmail'],
    };
}

export function ChangeUnverifiedEmailDtoToJSON(json: any): ChangeUnverifiedEmailDto {
    return ChangeUnverifiedEmailDtoToJSONTyped(json, false);
}

export function ChangeUnverifiedEmailDtoToJSONTyped(value?: ChangeUnverifiedEmailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldEmail': value['oldEmail'],
        'newEmail': value['newEmail'],
    };
}

