/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeMyAddressDto
 */
export interface ChangeMyAddressDto {
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    line1: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    line2: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    line3: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    line4: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    province: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMyAddressDto
     */
    country: string;
}

/**
 * Check if a given object implements the ChangeMyAddressDto interface.
 */
export function instanceOfChangeMyAddressDto(value: object): value is ChangeMyAddressDto {
    if (!('line1' in value) || value['line1'] === undefined) return false;
    if (!('line2' in value) || value['line2'] === undefined) return false;
    if (!('line3' in value) || value['line3'] === undefined) return false;
    if (!('line4' in value) || value['line4'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('province' in value) || value['province'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function ChangeMyAddressDtoFromJSON(json: any): ChangeMyAddressDto {
    return ChangeMyAddressDtoFromJSONTyped(json, false);
}

export function ChangeMyAddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeMyAddressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'line1': json['line1'],
        'line2': json['line2'],
        'line3': json['line3'],
        'line4': json['line4'],
        'city': json['city'],
        'postalCode': json['postalCode'],
        'province': json['province'],
        'country': json['country'],
    };
}

export function ChangeMyAddressDtoToJSON(json: any): ChangeMyAddressDto {
    return ChangeMyAddressDtoToJSONTyped(json, false);
}

export function ChangeMyAddressDtoToJSONTyped(value?: ChangeMyAddressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'line1': value['line1'],
        'line2': value['line2'],
        'line3': value['line3'],
        'line4': value['line4'],
        'city': value['city'],
        'postalCode': value['postalCode'],
        'province': value['province'],
        'country': value['country'],
    };
}

