/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckPortInDto
 */
export interface CheckPortInDto {
    /**
     * 
     * @type {string}
     * @memberof CheckPortInDto
     */
    msisdn: string;
}

/**
 * Check if a given object implements the CheckPortInDto interface.
 */
export function instanceOfCheckPortInDto(value: object): value is CheckPortInDto {
    if (!('msisdn' in value) || value['msisdn'] === undefined) return false;
    return true;
}

export function CheckPortInDtoFromJSON(json: any): CheckPortInDto {
    return CheckPortInDtoFromJSONTyped(json, false);
}

export function CheckPortInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckPortInDto {
    if (json == null) {
        return json;
    }
    return {
        
        'msisdn': json['msisdn'],
    };
}

export function CheckPortInDtoToJSON(json: any): CheckPortInDto {
    return CheckPortInDtoToJSONTyped(json, false);
}

export function CheckPortInDtoToJSONTyped(value?: CheckPortInDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'msisdn': value['msisdn'],
    };
}

