/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentBlockDto
 */
export interface ContentBlockDto {
    /**
     * 
     * @type {string}
     * @memberof ContentBlockDto
     */
    type: string;
}

/**
 * Check if a given object implements the ContentBlockDto interface.
 */
export function instanceOfContentBlockDto(value: object): value is ContentBlockDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ContentBlockDtoFromJSON(json: any): ContentBlockDto {
    return ContentBlockDtoFromJSONTyped(json, false);
}

export function ContentBlockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentBlockDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function ContentBlockDtoToJSON(json: any): ContentBlockDto {
    return ContentBlockDtoToJSONTyped(json, false);
}

export function ContentBlockDtoToJSONTyped(value?: ContentBlockDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

