/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentBlockSeparatorDto
 */
export interface ContentBlockSeparatorDto {
    /**
     * 
     * @type {string}
     * @memberof ContentBlockSeparatorDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ContentBlockSeparatorDto
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentBlockSeparatorDto
     */
    type: string;
}

/**
 * Check if a given object implements the ContentBlockSeparatorDto interface.
 */
export function instanceOfContentBlockSeparatorDto(value: object): value is ContentBlockSeparatorDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ContentBlockSeparatorDtoFromJSON(json: any): ContentBlockSeparatorDto {
    return ContentBlockSeparatorDtoFromJSONTyped(json, false);
}

export function ContentBlockSeparatorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentBlockSeparatorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'color': json['color'] == null ? undefined : json['color'],
        'type': json['type'],
    };
}

export function ContentBlockSeparatorDtoToJSON(json: any): ContentBlockSeparatorDto {
    return ContentBlockSeparatorDtoToJSONTyped(json, false);
}

export function ContentBlockSeparatorDtoToJSONTyped(value?: ContentBlockSeparatorDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'color': value['color'],
        'type': value['type'],
    };
}

