/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentBlockListDto
 */
export interface ContentBlockListDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentBlockListDto
     */
    content: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentBlockListDto
     */
    items: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ContentBlockListDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentBlockListDto
     */
    variant?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentBlockListDto
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentBlockListDto
     */
    type: string;
}

/**
 * Check if a given object implements the ContentBlockListDto interface.
 */
export function instanceOfContentBlockListDto(value: object): value is ContentBlockListDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ContentBlockListDtoFromJSON(json: any): ContentBlockListDto {
    return ContentBlockListDtoFromJSONTyped(json, false);
}

export function ContentBlockListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentBlockListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'items': json['items'],
        'title': json['title'] == null ? undefined : json['title'],
        'variant': json['variant'] == null ? undefined : json['variant'],
        'color': json['color'] == null ? undefined : json['color'],
        'type': json['type'],
    };
}

export function ContentBlockListDtoToJSON(json: any): ContentBlockListDto {
    return ContentBlockListDtoToJSONTyped(json, false);
}

export function ContentBlockListDtoToJSONTyped(value?: ContentBlockListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'items': value['items'],
        'title': value['title'],
        'variant': value['variant'],
        'color': value['color'],
        'type': value['type'],
    };
}

