/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletProvider } from './WalletProvider';
import {
    WalletProviderFromJSON,
    WalletProviderFromJSONTyped,
    WalletProviderToJSON,
    WalletProviderToJSONTyped,
} from './WalletProvider';

/**
 * 
 * @export
 * @interface CreateMyWalletDto
 */
export interface CreateMyWalletDto {
    /**
     * 
     * @type {WalletProvider}
     * @memberof CreateMyWalletDto
     */
    provider: WalletProvider;
    /**
     * 
     * @type {string}
     * @memberof CreateMyWalletDto
     */
    address: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMyWalletDto
     */
    imported: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMyWalletDto
     */
    readOnly: boolean;
}



/**
 * Check if a given object implements the CreateMyWalletDto interface.
 */
export function instanceOfCreateMyWalletDto(value: object): value is CreateMyWalletDto {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('imported' in value) || value['imported'] === undefined) return false;
    if (!('readOnly' in value) || value['readOnly'] === undefined) return false;
    return true;
}

export function CreateMyWalletDtoFromJSON(json: any): CreateMyWalletDto {
    return CreateMyWalletDtoFromJSONTyped(json, false);
}

export function CreateMyWalletDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMyWalletDto {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': WalletProviderFromJSON(json['provider']),
        'address': json['address'],
        'imported': json['imported'],
        'readOnly': json['readOnly'],
    };
}

export function CreateMyWalletDtoToJSON(json: any): CreateMyWalletDto {
    return CreateMyWalletDtoToJSONTyped(json, false);
}

export function CreateMyWalletDtoToJSONTyped(value?: CreateMyWalletDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': WalletProviderToJSON(value['provider']),
        'address': value['address'],
        'imported': value['imported'],
        'readOnly': value['readOnly'],
    };
}

