/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderType } from './OrderType';
import {
    OrderTypeFromJSON,
    OrderTypeFromJSONTyped,
    OrderTypeToJSON,
    OrderTypeToJSONTyped,
} from './OrderType';

/**
 * 
 * @export
 * @interface CreateMyOrderDto
 */
export interface CreateMyOrderDto {
    /**
     * 
     * @type {OrderType}
     * @memberof CreateMyOrderDto
     */
    type: OrderType;
    /**
     * 
     * @type {string}
     * @memberof CreateMyOrderDto
     */
    offerId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMyOrderDto
     */
    promoCodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMyOrderDto
     */
    subscriptionId?: string;
}



/**
 * Check if a given object implements the CreateMyOrderDto interface.
 */
export function instanceOfCreateMyOrderDto(value: object): value is CreateMyOrderDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateMyOrderDtoFromJSON(json: any): CreateMyOrderDto {
    return CreateMyOrderDtoFromJSONTyped(json, false);
}

export function CreateMyOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMyOrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': OrderTypeFromJSON(json['type']),
        'offerId': json['offerId'] == null ? undefined : json['offerId'],
        'promoCodeId': json['promoCodeId'] == null ? undefined : json['promoCodeId'],
        'subscriptionId': json['subscriptionId'] == null ? undefined : json['subscriptionId'],
    };
}

export function CreateMyOrderDtoToJSON(json: any): CreateMyOrderDto {
    return CreateMyOrderDtoToJSONTyped(json, false);
}

export function CreateMyOrderDtoToJSONTyped(value?: CreateMyOrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': OrderTypeToJSON(value['type']),
        'offerId': value['offerId'],
        'promoCodeId': value['promoCodeId'],
        'subscriptionId': value['subscriptionId'],
    };
}

