/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DeviceType = {
    Ios: 'IOS',
    Android: 'ANDROID'
} as const;
export type DeviceType = typeof DeviceType[keyof typeof DeviceType];


export function instanceOfDeviceType(value: any): boolean {
    for (const key in DeviceType) {
        if (Object.prototype.hasOwnProperty.call(DeviceType, key)) {
            if (DeviceType[key as keyof typeof DeviceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DeviceTypeFromJSON(json: any): DeviceType {
    return DeviceTypeFromJSONTyped(json, false);
}

export function DeviceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceType {
    return json as DeviceType;
}

export function DeviceTypeToJSON(value?: DeviceType | null): any {
    return value as any;
}

export function DeviceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DeviceType {
    return value as DeviceType;
}

