/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheckV1200ResponseInfoValue
 */
export interface HealthCheckV1200ResponseInfoValue {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof HealthCheckV1200ResponseInfoValue
     */
    status: string;
}

/**
 * Check if a given object implements the HealthCheckV1200ResponseInfoValue interface.
 */
export function instanceOfHealthCheckV1200ResponseInfoValue(value: object): value is HealthCheckV1200ResponseInfoValue {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthCheckV1200ResponseInfoValueFromJSON(json: any): HealthCheckV1200ResponseInfoValue {
    return HealthCheckV1200ResponseInfoValueFromJSONTyped(json, false);
}

export function HealthCheckV1200ResponseInfoValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckV1200ResponseInfoValue {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'status': json['status'],
    };
}

export function HealthCheckV1200ResponseInfoValueToJSON(json: any): HealthCheckV1200ResponseInfoValue {
    return HealthCheckV1200ResponseInfoValueToJSONTyped(json, false);
}

export function HealthCheckV1200ResponseInfoValueToJSONTyped(value?: HealthCheckV1200ResponseInfoValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'status': value['status'],
    };
}

