/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnboardingDataDto
 */
export interface OnboardingDataDto {
    /**
     * 
     * @type {string}
     * @memberof OnboardingDataDto
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingDataDto
     */
    showInProgress?: boolean;
}

/**
 * Check if a given object implements the OnboardingDataDto interface.
 */
export function instanceOfOnboardingDataDto(value: object): value is OnboardingDataDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function OnboardingDataDtoFromJSON(json: any): OnboardingDataDto {
    return OnboardingDataDtoFromJSONTyped(json, false);
}

export function OnboardingDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'showInProgress': json['showInProgress'] == null ? undefined : json['showInProgress'],
    };
}

export function OnboardingDataDtoToJSON(json: any): OnboardingDataDto {
    return OnboardingDataDtoToJSONTyped(json, false);
}

export function OnboardingDataDtoToJSONTyped(value?: OnboardingDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'showInProgress': value['showInProgress'],
    };
}

