/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnboardingDataOrderConfirmDto
 */
export interface OnboardingDataOrderConfirmDto {
    /**
     * 
     * @type {string}
     * @memberof OnboardingDataOrderConfirmDto
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingDataOrderConfirmDto
     */
    showInProgress?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingDataOrderConfirmDto
     */
    payment?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof OnboardingDataOrderConfirmDto
     */
    stages: Array<string>;
}

/**
 * Check if a given object implements the OnboardingDataOrderConfirmDto interface.
 */
export function instanceOfOnboardingDataOrderConfirmDto(value: object): value is OnboardingDataOrderConfirmDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('stages' in value) || value['stages'] === undefined) return false;
    return true;
}

export function OnboardingDataOrderConfirmDtoFromJSON(json: any): OnboardingDataOrderConfirmDto {
    return OnboardingDataOrderConfirmDtoFromJSONTyped(json, false);
}

export function OnboardingDataOrderConfirmDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingDataOrderConfirmDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'showInProgress': json['showInProgress'] == null ? undefined : json['showInProgress'],
        'payment': json['payment'] == null ? undefined : json['payment'],
        'stages': json['stages'],
    };
}

export function OnboardingDataOrderConfirmDtoToJSON(json: any): OnboardingDataOrderConfirmDto {
    return OnboardingDataOrderConfirmDtoToJSONTyped(json, false);
}

export function OnboardingDataOrderConfirmDtoToJSONTyped(value?: OnboardingDataOrderConfirmDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'showInProgress': value['showInProgress'],
        'payment': value['payment'],
        'stages': value['stages'],
    };
}

