/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OnboardingStageType = {
    Content: 'CONTENT',
    Address: 'ADDRESS',
    Payment: 'PAYMENT',
    OrderPlan: 'ORDER_PLAN',
    OrderMsisdn: 'ORDER_MSISDN',
    OrderSimType: 'ORDER_SIM_TYPE',
    OrderConfirm: 'ORDER_CONFIRM',
    OrderProcess: 'ORDER_PROCESS',
    Kyc: 'KYC'
} as const;
export type OnboardingStageType = typeof OnboardingStageType[keyof typeof OnboardingStageType];


export function instanceOfOnboardingStageType(value: any): boolean {
    for (const key in OnboardingStageType) {
        if (Object.prototype.hasOwnProperty.call(OnboardingStageType, key)) {
            if (OnboardingStageType[key as keyof typeof OnboardingStageType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OnboardingStageTypeFromJSON(json: any): OnboardingStageType {
    return OnboardingStageTypeFromJSONTyped(json, false);
}

export function OnboardingStageTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingStageType {
    return json as OnboardingStageType;
}

export function OnboardingStageTypeToJSON(value?: OnboardingStageType | null): any {
    return value as any;
}

export function OnboardingStageTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OnboardingStageType {
    return value as OnboardingStageType;
}

