/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressType } from './AddressType';
import {
    AddressTypeFromJSON,
    AddressTypeFromJSONTyped,
    AddressTypeToJSON,
    AddressTypeToJSONTyped,
} from './AddressType';

/**
 * 
 * @export
 * @interface OnboardingDataAddressDto
 */
export interface OnboardingDataAddressDto {
    /**
     * 
     * @type {AddressType}
     * @memberof OnboardingDataAddressDto
     */
    addressType: AddressType;
    /**
     * 
     * @type {string}
     * @memberof OnboardingDataAddressDto
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingDataAddressDto
     */
    showInProgress?: boolean;
}



/**
 * Check if a given object implements the OnboardingDataAddressDto interface.
 */
export function instanceOfOnboardingDataAddressDto(value: object): value is OnboardingDataAddressDto {
    if (!('addressType' in value) || value['addressType'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function OnboardingDataAddressDtoFromJSON(json: any): OnboardingDataAddressDto {
    return OnboardingDataAddressDtoFromJSONTyped(json, false);
}

export function OnboardingDataAddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingDataAddressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'addressType': AddressTypeFromJSON(json['addressType']),
        'type': json['type'],
        'showInProgress': json['showInProgress'] == null ? undefined : json['showInProgress'],
    };
}

export function OnboardingDataAddressDtoToJSON(json: any): OnboardingDataAddressDto {
    return OnboardingDataAddressDtoToJSONTyped(json, false);
}

export function OnboardingDataAddressDtoToJSONTyped(value?: OnboardingDataAddressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressType': AddressTypeToJSON(value['addressType']),
        'type': value['type'],
        'showInProgress': value['showInProgress'],
    };
}

