/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderType = {
    AddPlan: 'ADD_PLAN',
    RenewPlan: 'RENEW_PLAN',
    ChangePlan: 'CHANGE_PLAN',
    ChangeSim: 'CHANGE_SIM',
    ChangePhoneNumber: 'CHANGE_PHONE_NUMBER',
    DeactivatePlan: 'DEACTIVATE_PLAN',
    ReactivatePlan: 'REACTIVATE_PLAN',
    PortIn: 'PORT_IN',
    PortOut: 'PORT_OUT'
} as const;
export type OrderType = typeof OrderType[keyof typeof OrderType];


export function instanceOfOrderType(value: any): boolean {
    for (const key in OrderType) {
        if (Object.prototype.hasOwnProperty.call(OrderType, key)) {
            if (OrderType[key as keyof typeof OrderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrderTypeFromJSON(json: any): OrderType {
    return OrderTypeFromJSONTyped(json, false);
}

export function OrderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderType {
    return json as OrderType;
}

export function OrderTypeToJSON(value?: OrderType | null): any {
    return value as any;
}

export function OrderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OrderType {
    return value as OrderType;
}

