/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderStepStatus = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Error: 'ERROR',
    Done: 'DONE',
    Aborted: 'ABORTED',
    Skipped: 'SKIPPED'
} as const;
export type OrderStepStatus = typeof OrderStepStatus[keyof typeof OrderStepStatus];


export function instanceOfOrderStepStatus(value: any): boolean {
    for (const key in OrderStepStatus) {
        if (Object.prototype.hasOwnProperty.call(OrderStepStatus, key)) {
            if (OrderStepStatus[key as keyof typeof OrderStepStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrderStepStatusFromJSON(json: any): OrderStepStatus {
    return OrderStepStatusFromJSONTyped(json, false);
}

export function OrderStepStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStepStatus {
    return json as OrderStepStatus;
}

export function OrderStepStatusToJSON(value?: OrderStepStatus | null): any {
    return value as any;
}

export function OrderStepStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OrderStepStatus {
    return value as OrderStepStatus;
}

