/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortInDto
 */
export interface PortInDto {
    /**
     * 
     * @type {boolean}
     * @memberof PortInDto
     */
    isPortingIn: boolean;
    /**
     * 
     * @type {string}
     * @memberof PortInDto
     */
    msisdn?: string;
    /**
     * 
     * @type {string}
     * @memberof PortInDto
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PortInDto
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PortInDto
     */
    password?: string;
}

/**
 * Check if a given object implements the PortInDto interface.
 */
export function instanceOfPortInDto(value: object): value is PortInDto {
    if (!('isPortingIn' in value) || value['isPortingIn'] === undefined) return false;
    return true;
}

export function PortInDtoFromJSON(json: any): PortInDto {
    return PortInDtoFromJSONTyped(json, false);
}

export function PortInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortInDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isPortingIn': json['isPortingIn'],
        'msisdn': json['msisdn'] == null ? undefined : json['msisdn'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function PortInDtoToJSON(json: any): PortInDto {
    return PortInDtoToJSONTyped(json, false);
}

export function PortInDtoToJSONTyped(value?: PortInDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPortingIn': value['isPortingIn'],
        'msisdn': value['msisdn'],
        'postalCode': value['postalCode'],
        'accountNumber': value['accountNumber'],
        'password': value['password'],
    };
}

