/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicSessionTokensDto
 */
export interface PublicSessionTokensDto {
    /**
     * 
     * @type {string}
     * @memberof PublicSessionTokensDto
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSessionTokensDto
     */
    expires: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSessionTokensDto
     */
    refreshToken: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSessionTokensDto
     */
    refreshExpires: string;
}

/**
 * Check if a given object implements the PublicSessionTokensDto interface.
 */
export function instanceOfPublicSessionTokensDto(value: object): value is PublicSessionTokensDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expires' in value) || value['expires'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('refreshExpires' in value) || value['refreshExpires'] === undefined) return false;
    return true;
}

export function PublicSessionTokensDtoFromJSON(json: any): PublicSessionTokensDto {
    return PublicSessionTokensDtoFromJSONTyped(json, false);
}

export function PublicSessionTokensDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSessionTokensDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expires': json['expires'],
        'refreshToken': json['refreshToken'],
        'refreshExpires': json['refreshExpires'],
    };
}

export function PublicSessionTokensDtoToJSON(json: any): PublicSessionTokensDto {
    return PublicSessionTokensDtoToJSONTyped(json, false);
}

export function PublicSessionTokensDtoToJSONTyped(value?: PublicSessionTokensDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expires': value['expires'],
        'refreshToken': value['refreshToken'],
        'refreshExpires': value['refreshExpires'],
    };
}

