/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionStatus } from './SubscriptionStatus';
import {
    SubscriptionStatusFromJSON,
    SubscriptionStatusFromJSONTyped,
    SubscriptionStatusToJSON,
    SubscriptionStatusToJSONTyped,
} from './SubscriptionStatus';
import type { PublicOfferWithPlanDto } from './PublicOfferWithPlanDto';
import {
    PublicOfferWithPlanDtoFromJSON,
    PublicOfferWithPlanDtoFromJSONTyped,
    PublicOfferWithPlanDtoToJSON,
    PublicOfferWithPlanDtoToJSONTyped,
} from './PublicOfferWithPlanDto';
import type { PublicSubscriptionPeriodDto } from './PublicSubscriptionPeriodDto';
import {
    PublicSubscriptionPeriodDtoFromJSON,
    PublicSubscriptionPeriodDtoFromJSONTyped,
    PublicSubscriptionPeriodDtoToJSON,
    PublicSubscriptionPeriodDtoToJSONTyped,
} from './PublicSubscriptionPeriodDto';

/**
 * 
 * @export
 * @interface PublicSubscriptionWithOfferDto
 */
export interface PublicSubscriptionWithOfferDto {
    /**
     * 
     * @type {SubscriptionStatus}
     * @memberof PublicSubscriptionWithOfferDto
     */
    status: SubscriptionStatus;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionWithOfferDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionWithOfferDto
     */
    parentId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionWithOfferDto
     */
    label: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionWithOfferDto
     */
    phoneNumberMsisdn: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionWithOfferDto
     */
    simIccid: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionWithOfferDto
     */
    userId: string;
    /**
     * 
     * @type {PublicSubscriptionPeriodDto}
     * @memberof PublicSubscriptionWithOfferDto
     */
    currentPeriod: PublicSubscriptionPeriodDto | null;
    /**
     * 
     * @type {PublicOfferWithPlanDto}
     * @memberof PublicSubscriptionWithOfferDto
     */
    offer: PublicOfferWithPlanDto;
}



/**
 * Check if a given object implements the PublicSubscriptionWithOfferDto interface.
 */
export function instanceOfPublicSubscriptionWithOfferDto(value: object): value is PublicSubscriptionWithOfferDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('phoneNumberMsisdn' in value) || value['phoneNumberMsisdn'] === undefined) return false;
    if (!('simIccid' in value) || value['simIccid'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('currentPeriod' in value) || value['currentPeriod'] === undefined) return false;
    if (!('offer' in value) || value['offer'] === undefined) return false;
    return true;
}

export function PublicSubscriptionWithOfferDtoFromJSON(json: any): PublicSubscriptionWithOfferDto {
    return PublicSubscriptionWithOfferDtoFromJSONTyped(json, false);
}

export function PublicSubscriptionWithOfferDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSubscriptionWithOfferDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': SubscriptionStatusFromJSON(json['status']),
        'id': json['id'],
        'parentId': json['parentId'],
        'label': json['label'],
        'phoneNumberMsisdn': json['phoneNumberMsisdn'],
        'simIccid': json['simIccid'],
        'userId': json['userId'],
        'currentPeriod': PublicSubscriptionPeriodDtoFromJSON(json['currentPeriod']),
        'offer': PublicOfferWithPlanDtoFromJSON(json['offer']),
    };
}

export function PublicSubscriptionWithOfferDtoToJSON(json: any): PublicSubscriptionWithOfferDto {
    return PublicSubscriptionWithOfferDtoToJSONTyped(json, false);
}

export function PublicSubscriptionWithOfferDtoToJSONTyped(value?: PublicSubscriptionWithOfferDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': SubscriptionStatusToJSON(value['status']),
        'id': value['id'],
        'parentId': value['parentId'],
        'label': value['label'],
        'phoneNumberMsisdn': value['phoneNumberMsisdn'],
        'simIccid': value['simIccid'],
        'userId': value['userId'],
        'currentPeriod': PublicSubscriptionPeriodDtoToJSON(value['currentPeriod']),
        'offer': PublicOfferWithPlanDtoToJSON(value['offer']),
    };
}

