/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicTokenHistoryEntryDto } from './PublicTokenHistoryEntryDto';
import {
    PublicTokenHistoryEntryDtoFromJSON,
    PublicTokenHistoryEntryDtoFromJSONTyped,
    PublicTokenHistoryEntryDtoToJSON,
    PublicTokenHistoryEntryDtoToJSONTyped,
} from './PublicTokenHistoryEntryDto';

/**
 * 
 * @export
 * @interface PublicTokenHistoryDto
 */
export interface PublicTokenHistoryDto {
    /**
     * 
     * @type {Array<PublicTokenHistoryEntryDto>}
     * @memberof PublicTokenHistoryDto
     */
    prices: Array<PublicTokenHistoryEntryDto>;
}

/**
 * Check if a given object implements the PublicTokenHistoryDto interface.
 */
export function instanceOfPublicTokenHistoryDto(value: object): value is PublicTokenHistoryDto {
    if (!('prices' in value) || value['prices'] === undefined) return false;
    return true;
}

export function PublicTokenHistoryDtoFromJSON(json: any): PublicTokenHistoryDto {
    return PublicTokenHistoryDtoFromJSONTyped(json, false);
}

export function PublicTokenHistoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTokenHistoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'prices': ((json['prices'] as Array<any>).map(PublicTokenHistoryEntryDtoFromJSON)),
    };
}

export function PublicTokenHistoryDtoToJSON(json: any): PublicTokenHistoryDto {
    return PublicTokenHistoryDtoToJSONTyped(json, false);
}

export function PublicTokenHistoryDtoToJSONTyped(value?: PublicTokenHistoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prices': ((value['prices'] as Array<any>).map(PublicTokenHistoryEntryDtoToJSON)),
    };
}

