/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStepStatus } from './OrderStepStatus';
import {
    OrderStepStatusFromJSON,
    OrderStepStatusFromJSONTyped,
    OrderStepStatusToJSON,
    OrderStepStatusToJSONTyped,
} from './OrderStepStatus';

/**
 * 
 * @export
 * @interface PublicOrderStepDto
 */
export interface PublicOrderStepDto {
    /**
     * 
     * @type {OrderStepStatus}
     * @memberof PublicOrderStepDto
     */
    status: OrderStepStatus;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderStepDto
     */
    error: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderStepDto
     */
    type: string;
}



/**
 * Check if a given object implements the PublicOrderStepDto interface.
 */
export function instanceOfPublicOrderStepDto(value: object): value is PublicOrderStepDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PublicOrderStepDtoFromJSON(json: any): PublicOrderStepDto {
    return PublicOrderStepDtoFromJSONTyped(json, false);
}

export function PublicOrderStepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOrderStepDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OrderStepStatusFromJSON(json['status']),
        'error': json['error'],
        'type': json['type'],
    };
}

export function PublicOrderStepDtoToJSON(json: any): PublicOrderStepDto {
    return PublicOrderStepDtoToJSONTyped(json, false);
}

export function PublicOrderStepDtoToJSONTyped(value?: PublicOrderStepDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OrderStepStatusToJSON(value['status']),
        'error': value['error'],
        'type': value['type'],
    };
}

