/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicOnboardingProgressDto
 */
export interface PublicOnboardingProgressDto {
    /**
     * 
     * @type {string}
     * @memberof PublicOnboardingProgressDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOnboardingProgressDto
     */
    stageName: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicOnboardingProgressDto
     */
    startedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PublicOnboardingProgressDto
     */
    completedAt: Date | null;
}

/**
 * Check if a given object implements the PublicOnboardingProgressDto interface.
 */
export function instanceOfPublicOnboardingProgressDto(value: object): value is PublicOnboardingProgressDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('stageName' in value) || value['stageName'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    return true;
}

export function PublicOnboardingProgressDtoFromJSON(json: any): PublicOnboardingProgressDto {
    return PublicOnboardingProgressDtoFromJSONTyped(json, false);
}

export function PublicOnboardingProgressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOnboardingProgressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'stageName': json['stageName'],
        'startedAt': (json['startedAt'] == null ? null : new Date(json['startedAt'])),
        'completedAt': (json['completedAt'] == null ? null : new Date(json['completedAt'])),
    };
}

export function PublicOnboardingProgressDtoToJSON(json: any): PublicOnboardingProgressDto {
    return PublicOnboardingProgressDtoToJSONTyped(json, false);
}

export function PublicOnboardingProgressDtoToJSONTyped(value?: PublicOnboardingProgressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stageName': value['stageName'],
        'startedAt': (value['startedAt'] == null ? null : (value['startedAt'] as any).toISOString()),
        'completedAt': (value['completedAt'] == null ? null : (value['completedAt'] as any).toISOString()),
    };
}

