/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionStatus } from './SubscriptionStatus';
import {
    SubscriptionStatusFromJSON,
    SubscriptionStatusFromJSONTyped,
    SubscriptionStatusToJSON,
    SubscriptionStatusToJSONTyped,
} from './SubscriptionStatus';

/**
 * 
 * @export
 * @interface PublicSubscriptionDto
 */
export interface PublicSubscriptionDto {
    /**
     * 
     * @type {SubscriptionStatus}
     * @memberof PublicSubscriptionDto
     */
    status: SubscriptionStatus;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionDto
     */
    parentId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionDto
     */
    label: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionDto
     */
    phoneNumberMsisdn: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionDto
     */
    simIccid: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionDto
     */
    userId: string;
}



/**
 * Check if a given object implements the PublicSubscriptionDto interface.
 */
export function instanceOfPublicSubscriptionDto(value: object): value is PublicSubscriptionDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('phoneNumberMsisdn' in value) || value['phoneNumberMsisdn'] === undefined) return false;
    if (!('simIccid' in value) || value['simIccid'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function PublicSubscriptionDtoFromJSON(json: any): PublicSubscriptionDto {
    return PublicSubscriptionDtoFromJSONTyped(json, false);
}

export function PublicSubscriptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSubscriptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': SubscriptionStatusFromJSON(json['status']),
        'id': json['id'],
        'parentId': json['parentId'],
        'label': json['label'],
        'phoneNumberMsisdn': json['phoneNumberMsisdn'],
        'simIccid': json['simIccid'],
        'userId': json['userId'],
    };
}

export function PublicSubscriptionDtoToJSON(json: any): PublicSubscriptionDto {
    return PublicSubscriptionDtoToJSONTyped(json, false);
}

export function PublicSubscriptionDtoToJSONTyped(value?: PublicSubscriptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': SubscriptionStatusToJSON(value['status']),
        'id': value['id'],
        'parentId': value['parentId'],
        'label': value['label'],
        'phoneNumberMsisdn': value['phoneNumberMsisdn'],
        'simIccid': value['simIccid'],
        'userId': value['userId'],
    };
}

