/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicOrderSigningDto
 */
export interface PublicOrderSigningDto {
    /**
     * 
     * @type {string}
     * @memberof PublicOrderSigningDto
     */
    message: string | null;
}

/**
 * Check if a given object implements the PublicOrderSigningDto interface.
 */
export function instanceOfPublicOrderSigningDto(value: object): value is PublicOrderSigningDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PublicOrderSigningDtoFromJSON(json: any): PublicOrderSigningDto {
    return PublicOrderSigningDtoFromJSONTyped(json, false);
}

export function PublicOrderSigningDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOrderSigningDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function PublicOrderSigningDtoToJSON(json: any): PublicOrderSigningDto {
    return PublicOrderSigningDtoToJSONTyped(json, false);
}

export function PublicOrderSigningDtoToJSONTyped(value?: PublicOrderSigningDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

