/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimType } from './SimType';
import {
    SimTypeFromJSON,
    SimTypeFromJSONTyped,
    SimTypeToJSON,
    SimTypeToJSONTyped,
} from './SimType';

/**
 * 
 * @export
 * @interface PublicSimSelectionDataDto
 */
export interface PublicSimSelectionDataDto {
    /**
     * 
     * @type {SimType}
     * @memberof PublicSimSelectionDataDto
     */
    simType: SimType;
    /**
     * 
     * @type {string}
     * @memberof PublicSimSelectionDataDto
     */
    iccid?: string | null;
}



/**
 * Check if a given object implements the PublicSimSelectionDataDto interface.
 */
export function instanceOfPublicSimSelectionDataDto(value: object): value is PublicSimSelectionDataDto {
    if (!('simType' in value) || value['simType'] === undefined) return false;
    return true;
}

export function PublicSimSelectionDataDtoFromJSON(json: any): PublicSimSelectionDataDto {
    return PublicSimSelectionDataDtoFromJSONTyped(json, false);
}

export function PublicSimSelectionDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSimSelectionDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'simType': SimTypeFromJSON(json['simType']),
        'iccid': json['iccid'] == null ? undefined : json['iccid'],
    };
}

export function PublicSimSelectionDataDtoToJSON(json: any): PublicSimSelectionDataDto {
    return PublicSimSelectionDataDtoToJSONTyped(json, false);
}

export function PublicSimSelectionDataDtoToJSONTyped(value?: PublicSimSelectionDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simType': SimTypeToJSON(value['simType']),
        'iccid': value['iccid'],
    };
}

