/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicPortInDataDto
 */
export interface PublicPortInDataDto {
    /**
     * 
     * @type {boolean}
     * @memberof PublicPortInDataDto
     */
    isPortingIn: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicPortInDataDto
     */
    msisdn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicPortInDataDto
     */
    postalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicPortInDataDto
     */
    accountNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicPortInDataDto
     */
    password?: string | null;
}

/**
 * Check if a given object implements the PublicPortInDataDto interface.
 */
export function instanceOfPublicPortInDataDto(value: object): value is PublicPortInDataDto {
    if (!('isPortingIn' in value) || value['isPortingIn'] === undefined) return false;
    return true;
}

export function PublicPortInDataDtoFromJSON(json: any): PublicPortInDataDto {
    return PublicPortInDataDtoFromJSONTyped(json, false);
}

export function PublicPortInDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPortInDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isPortingIn': json['isPortingIn'],
        'msisdn': json['msisdn'] == null ? undefined : json['msisdn'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function PublicPortInDataDtoToJSON(json: any): PublicPortInDataDto {
    return PublicPortInDataDtoToJSONTyped(json, false);
}

export function PublicPortInDataDtoToJSONTyped(value?: PublicPortInDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPortingIn': value['isPortingIn'],
        'msisdn': value['msisdn'],
        'postalCode': value['postalCode'],
        'accountNumber': value['accountNumber'],
        'password': value['password'],
    };
}

