/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimType } from './SimType';
import {
    SimTypeFromJSON,
    SimTypeFromJSONTyped,
    SimTypeToJSON,
    SimTypeToJSONTyped,
} from './SimType';

/**
 * 
 * @export
 * @interface PublicSimDetailsDto
 */
export interface PublicSimDetailsDto {
    /**
     * 
     * @type {SimType}
     * @memberof PublicSimDetailsDto
     */
    type: SimType;
    /**
     * 
     * @type {boolean}
     * @memberof PublicSimDetailsDto
     */
    isActivated: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicSimDetailsDto
     */
    eSimStatus: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSimDetailsDto
     */
    eSimActivationCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSimDetailsDto
     */
    pin: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSimDetailsDto
     */
    puk: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicSimDetailsDto
     */
    iccid: string;
}



/**
 * Check if a given object implements the PublicSimDetailsDto interface.
 */
export function instanceOfPublicSimDetailsDto(value: object): value is PublicSimDetailsDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isActivated' in value) || value['isActivated'] === undefined) return false;
    if (!('eSimStatus' in value) || value['eSimStatus'] === undefined) return false;
    if (!('eSimActivationCode' in value) || value['eSimActivationCode'] === undefined) return false;
    if (!('pin' in value) || value['pin'] === undefined) return false;
    if (!('puk' in value) || value['puk'] === undefined) return false;
    if (!('iccid' in value) || value['iccid'] === undefined) return false;
    return true;
}

export function PublicSimDetailsDtoFromJSON(json: any): PublicSimDetailsDto {
    return PublicSimDetailsDtoFromJSONTyped(json, false);
}

export function PublicSimDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSimDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': SimTypeFromJSON(json['type']),
        'isActivated': json['isActivated'],
        'eSimStatus': json['eSimStatus'],
        'eSimActivationCode': json['eSimActivationCode'],
        'pin': json['pin'],
        'puk': json['puk'],
        'iccid': json['iccid'],
    };
}

export function PublicSimDetailsDtoToJSON(json: any): PublicSimDetailsDto {
    return PublicSimDetailsDtoToJSONTyped(json, false);
}

export function PublicSimDetailsDtoToJSONTyped(value?: PublicSimDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': SimTypeToJSON(value['type']),
        'isActivated': value['isActivated'],
        'eSimStatus': value['eSimStatus'],
        'eSimActivationCode': value['eSimActivationCode'],
        'pin': value['pin'],
        'puk': value['puk'],
        'iccid': value['iccid'],
    };
}

