/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicContentDto } from './PublicContentDto';
import {
    PublicContentDtoFromJSON,
    PublicContentDtoFromJSONTyped,
    PublicContentDtoToJSON,
    PublicContentDtoToJSONTyped,
} from './PublicContentDto';
import type { PublicOfferWithPlanWithVolumesDto } from './PublicOfferWithPlanWithVolumesDto';
import {
    PublicOfferWithPlanWithVolumesDtoFromJSON,
    PublicOfferWithPlanWithVolumesDtoFromJSONTyped,
    PublicOfferWithPlanWithVolumesDtoToJSON,
    PublicOfferWithPlanWithVolumesDtoToJSONTyped,
} from './PublicOfferWithPlanWithVolumesDto';

/**
 * 
 * @export
 * @interface PublicPromoCodeWithOffersDto
 */
export interface PublicPromoCodeWithOffersDto {
    /**
     * 
     * @type {PublicContentDto}
     * @memberof PublicPromoCodeWithOffersDto
     */
    content: PublicContentDto;
    /**
     * 
     * @type {string}
     * @memberof PublicPromoCodeWithOffersDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPromoCodeWithOffersDto
     */
    code: string;
    /**
     * 
     * @type {Array<PublicOfferWithPlanWithVolumesDto>}
     * @memberof PublicPromoCodeWithOffersDto
     */
    offers: Array<PublicOfferWithPlanWithVolumesDto>;
}

/**
 * Check if a given object implements the PublicPromoCodeWithOffersDto interface.
 */
export function instanceOfPublicPromoCodeWithOffersDto(value: object): value is PublicPromoCodeWithOffersDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('offers' in value) || value['offers'] === undefined) return false;
    return true;
}

export function PublicPromoCodeWithOffersDtoFromJSON(json: any): PublicPromoCodeWithOffersDto {
    return PublicPromoCodeWithOffersDtoFromJSONTyped(json, false);
}

export function PublicPromoCodeWithOffersDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPromoCodeWithOffersDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': PublicContentDtoFromJSON(json['content']),
        'id': json['id'],
        'code': json['code'],
        'offers': ((json['offers'] as Array<any>).map(PublicOfferWithPlanWithVolumesDtoFromJSON)),
    };
}

export function PublicPromoCodeWithOffersDtoToJSON(json: any): PublicPromoCodeWithOffersDto {
    return PublicPromoCodeWithOffersDtoToJSONTyped(json, false);
}

export function PublicPromoCodeWithOffersDtoToJSONTyped(value?: PublicPromoCodeWithOffersDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': PublicContentDtoToJSON(value['content']),
        'id': value['id'],
        'code': value['code'],
        'offers': ((value['offers'] as Array<any>).map(PublicOfferWithPlanWithVolumesDtoToJSON)),
    };
}

