/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicPortInDto
 */
export interface PublicPortInDto {
    /**
     * 
     * @type {boolean}
     * @memberof PublicPortInDto
     */
    isEligible: boolean;
}

/**
 * Check if a given object implements the PublicPortInDto interface.
 */
export function instanceOfPublicPortInDto(value: object): value is PublicPortInDto {
    if (!('isEligible' in value) || value['isEligible'] === undefined) return false;
    return true;
}

export function PublicPortInDtoFromJSON(json: any): PublicPortInDto {
    return PublicPortInDtoFromJSONTyped(json, false);
}

export function PublicPortInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPortInDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isEligible': json['isEligible'],
    };
}

export function PublicPortInDtoToJSON(json: any): PublicPortInDto {
    return PublicPortInDtoToJSONTyped(json, false);
}

export function PublicPortInDtoToJSONTyped(value?: PublicPortInDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isEligible': value['isEligible'],
    };
}

