/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicTokenBalanceDto
 */
export interface PublicTokenBalanceDto {
    /**
     * 
     * @type {string}
     * @memberof PublicTokenBalanceDto
     */
    exchangeRateUsd: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicTokenBalanceDto
     */
    balance: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTokenBalanceDto
     */
    balanceInUsd: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicTokenBalanceDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTokenBalanceDto
     */
    symbol: string;
    /**
     * 
     * @type {number}
     * @memberof PublicTokenBalanceDto
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof PublicTokenBalanceDto
     */
    image: string;
}

/**
 * Check if a given object implements the PublicTokenBalanceDto interface.
 */
export function instanceOfPublicTokenBalanceDto(value: object): value is PublicTokenBalanceDto {
    if (!('exchangeRateUsd' in value) || value['exchangeRateUsd'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('balanceInUsd' in value) || value['balanceInUsd'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function PublicTokenBalanceDtoFromJSON(json: any): PublicTokenBalanceDto {
    return PublicTokenBalanceDtoFromJSONTyped(json, false);
}

export function PublicTokenBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTokenBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'exchangeRateUsd': json['exchangeRateUsd'],
        'balance': json['balance'],
        'balanceInUsd': json['balanceInUsd'],
        'name': json['name'],
        'symbol': json['symbol'],
        'decimals': json['decimals'],
        'image': json['image'],
    };
}

export function PublicTokenBalanceDtoToJSON(json: any): PublicTokenBalanceDto {
    return PublicTokenBalanceDtoToJSONTyped(json, false);
}

export function PublicTokenBalanceDtoToJSONTyped(value?: PublicTokenBalanceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exchangeRateUsd': value['exchangeRateUsd'],
        'balance': value['balance'],
        'balanceInUsd': value['balanceInUsd'],
        'name': value['name'],
        'symbol': value['symbol'],
        'decimals': value['decimals'],
        'image': value['image'],
    };
}

