/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';
import type { OrderType } from './OrderType';
import {
    OrderTypeFromJSON,
    OrderTypeFromJSONTyped,
    OrderTypeToJSON,
    OrderTypeToJSONTyped,
} from './OrderType';
import type { PublicSubscriptionWithOfferDto } from './PublicSubscriptionWithOfferDto';
import {
    PublicSubscriptionWithOfferDtoFromJSON,
    PublicSubscriptionWithOfferDtoFromJSONTyped,
    PublicSubscriptionWithOfferDtoToJSON,
    PublicSubscriptionWithOfferDtoToJSONTyped,
} from './PublicSubscriptionWithOfferDto';

/**
 * 
 * @export
 * @interface PublicOrderWithSubscriptionDto
 */
export interface PublicOrderWithSubscriptionDto {
    /**
     * 
     * @type {OrderType}
     * @memberof PublicOrderWithSubscriptionDto
     */
    type: OrderType;
    /**
     * 
     * @type {OrderStatus}
     * @memberof PublicOrderWithSubscriptionDto
     */
    status: OrderStatus;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderWithSubscriptionDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicOrderWithSubscriptionDto
     */
    startedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PublicOrderWithSubscriptionDto
     */
    completedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOrderWithSubscriptionDto
     */
    subscriptionId: string | null;
    /**
     * 
     * @type {PublicSubscriptionWithOfferDto}
     * @memberof PublicOrderWithSubscriptionDto
     */
    subscription: PublicSubscriptionWithOfferDto | null;
}



/**
 * Check if a given object implements the PublicOrderWithSubscriptionDto interface.
 */
export function instanceOfPublicOrderWithSubscriptionDto(value: object): value is PublicOrderWithSubscriptionDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    if (!('subscription' in value) || value['subscription'] === undefined) return false;
    return true;
}

export function PublicOrderWithSubscriptionDtoFromJSON(json: any): PublicOrderWithSubscriptionDto {
    return PublicOrderWithSubscriptionDtoFromJSONTyped(json, false);
}

export function PublicOrderWithSubscriptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOrderWithSubscriptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': OrderTypeFromJSON(json['type']),
        'status': OrderStatusFromJSON(json['status']),
        'id': json['id'],
        'startedAt': (json['startedAt'] == null ? null : new Date(json['startedAt'])),
        'completedAt': (json['completedAt'] == null ? null : new Date(json['completedAt'])),
        'subscriptionId': json['subscriptionId'],
        'subscription': PublicSubscriptionWithOfferDtoFromJSON(json['subscription']),
    };
}

export function PublicOrderWithSubscriptionDtoToJSON(json: any): PublicOrderWithSubscriptionDto {
    return PublicOrderWithSubscriptionDtoToJSONTyped(json, false);
}

export function PublicOrderWithSubscriptionDtoToJSONTyped(value?: PublicOrderWithSubscriptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': OrderTypeToJSON(value['type']),
        'status': OrderStatusToJSON(value['status']),
        'id': value['id'],
        'startedAt': (value['startedAt'] == null ? null : (value['startedAt'] as any).toISOString()),
        'completedAt': (value['completedAt'] == null ? null : (value['completedAt'] as any).toISOString()),
        'subscriptionId': value['subscriptionId'],
        'subscription': PublicSubscriptionWithOfferDtoToJSON(value['subscription']),
    };
}

