/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicContentDto } from './PublicContentDto';
import {
    PublicContentDtoFromJSON,
    PublicContentDtoFromJSONTyped,
    PublicContentDtoToJSON,
    PublicContentDtoToJSONTyped,
} from './PublicContentDto';

/**
 * 
 * @export
 * @interface PublicPlanDto
 */
export interface PublicPlanDto {
    /**
     * 
     * @type {PublicContentDto}
     * @memberof PublicPlanDto
     */
    content: PublicContentDto;
    /**
     * 
     * @type {string}
     * @memberof PublicPlanDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPlanDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicPlanDto
     */
    isStandalone: boolean;
    /**
     * 
     * @type {number}
     * @memberof PublicPlanDto
     */
    validForSeconds: number;
    /**
     * 
     * @type {boolean}
     * @memberof PublicPlanDto
     */
    doesAutoRenew: boolean;
}

/**
 * Check if a given object implements the PublicPlanDto interface.
 */
export function instanceOfPublicPlanDto(value: object): value is PublicPlanDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isStandalone' in value) || value['isStandalone'] === undefined) return false;
    if (!('validForSeconds' in value) || value['validForSeconds'] === undefined) return false;
    if (!('doesAutoRenew' in value) || value['doesAutoRenew'] === undefined) return false;
    return true;
}

export function PublicPlanDtoFromJSON(json: any): PublicPlanDto {
    return PublicPlanDtoFromJSONTyped(json, false);
}

export function PublicPlanDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPlanDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': PublicContentDtoFromJSON(json['content']),
        'id': json['id'],
        'name': json['name'],
        'isStandalone': json['isStandalone'],
        'validForSeconds': json['validForSeconds'],
        'doesAutoRenew': json['doesAutoRenew'],
    };
}

export function PublicPlanDtoToJSON(json: any): PublicPlanDto {
    return PublicPlanDtoToJSONTyped(json, false);
}

export function PublicPlanDtoToJSONTyped(value?: PublicPlanDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': PublicContentDtoToJSON(value['content']),
        'id': value['id'],
        'name': value['name'],
        'isStandalone': value['isStandalone'],
        'validForSeconds': value['validForSeconds'],
        'doesAutoRenew': value['doesAutoRenew'],
    };
}

