/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicTaxItemDto
 */
export interface PublicTaxItemDto {
    /**
     * 
     * @type {string}
     * @memberof PublicTaxItemDto
     */
    cost: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTaxItemDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTaxItemDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTaxItemDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTaxItemDto
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublicTaxItemDto
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the PublicTaxItemDto interface.
 */
export function instanceOfPublicTaxItemDto(value: object): value is PublicTaxItemDto {
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function PublicTaxItemDtoFromJSON(json: any): PublicTaxItemDto {
    return PublicTaxItemDtoFromJSONTyped(json, false);
}

export function PublicTaxItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTaxItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'cost': json['cost'],
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'description': json['description'],
        'tags': json['tags'],
    };
}

export function PublicTaxItemDtoToJSON(json: any): PublicTaxItemDto {
    return PublicTaxItemDtoToJSONTyped(json, false);
}

export function PublicTaxItemDtoToJSONTyped(value?: PublicTaxItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cost': value['cost'],
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
    };
}

