/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicAuthGoogleExchangeDto
 */
export interface PublicAuthGoogleExchangeDto {
    /**
     * 
     * @type {string}
     * @memberof PublicAuthGoogleExchangeDto
     */
    issuerUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthGoogleExchangeDto
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthGoogleExchangeDto
     */
    redirectUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthGoogleExchangeDto
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthGoogleExchangeDto
     */
    webClientId: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthGoogleExchangeDto
     */
    iOSClientId: string;
}

/**
 * Check if a given object implements the PublicAuthGoogleExchangeDto interface.
 */
export function instanceOfPublicAuthGoogleExchangeDto(value: object): value is PublicAuthGoogleExchangeDto {
    if (!('issuerUrl' in value) || value['issuerUrl'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('redirectUrl' in value) || value['redirectUrl'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('webClientId' in value) || value['webClientId'] === undefined) return false;
    if (!('iOSClientId' in value) || value['iOSClientId'] === undefined) return false;
    return true;
}

export function PublicAuthGoogleExchangeDtoFromJSON(json: any): PublicAuthGoogleExchangeDto {
    return PublicAuthGoogleExchangeDtoFromJSONTyped(json, false);
}

export function PublicAuthGoogleExchangeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAuthGoogleExchangeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'issuerUrl': json['issuerUrl'],
        'clientId': json['clientId'],
        'redirectUrl': json['redirectUrl'],
        'scope': json['scope'],
        'webClientId': json['webClientId'],
        'iOSClientId': json['iOSClientId'],
    };
}

export function PublicAuthGoogleExchangeDtoToJSON(json: any): PublicAuthGoogleExchangeDto {
    return PublicAuthGoogleExchangeDtoToJSONTyped(json, false);
}

export function PublicAuthGoogleExchangeDtoToJSONTyped(value?: PublicAuthGoogleExchangeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuerUrl': value['issuerUrl'],
        'clientId': value['clientId'],
        'redirectUrl': value['redirectUrl'],
        'scope': value['scope'],
        'webClientId': value['webClientId'],
        'iOSClientId': value['iOSClientId'],
    };
}

