/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicUserSettingsDto
 */
export interface PublicUserSettingsDto {
    /**
     * 
     * @type {boolean}
     * @memberof PublicUserSettingsDto
     */
    email?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PublicUserSettingsDto
     */
    mail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PublicUserSettingsDto
     */
    sms?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PublicUserSettingsDto
     */
    cpni?: boolean;
}

/**
 * Check if a given object implements the PublicUserSettingsDto interface.
 */
export function instanceOfPublicUserSettingsDto(value: object): value is PublicUserSettingsDto {
    return true;
}

export function PublicUserSettingsDtoFromJSON(json: any): PublicUserSettingsDto {
    return PublicUserSettingsDtoFromJSONTyped(json, false);
}

export function PublicUserSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicUserSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'mail': json['mail'] == null ? undefined : json['mail'],
        'sms': json['sms'] == null ? undefined : json['sms'],
        'cpni': json['cpni'] == null ? undefined : json['cpni'],
    };
}

export function PublicUserSettingsDtoToJSON(json: any): PublicUserSettingsDto {
    return PublicUserSettingsDtoToJSONTyped(json, false);
}

export function PublicUserSettingsDtoToJSONTyped(value?: PublicUserSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'mail': value['mail'],
        'sms': value['sms'],
        'cpni': value['cpni'],
    };
}

