/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicInvoiceItemDto
 */
export interface PublicInvoiceItemDto {
    /**
     * 
     * @type {string}
     * @memberof PublicInvoiceItemDto
     */
    costPerItem: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvoiceItemDto
     */
    totalCost: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvoiceItemDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvoiceItemDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvoiceItemDto
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof PublicInvoiceItemDto
     */
    amount: number;
}

/**
 * Check if a given object implements the PublicInvoiceItemDto interface.
 */
export function instanceOfPublicInvoiceItemDto(value: object): value is PublicInvoiceItemDto {
    if (!('costPerItem' in value) || value['costPerItem'] === undefined) return false;
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function PublicInvoiceItemDtoFromJSON(json: any): PublicInvoiceItemDto {
    return PublicInvoiceItemDtoFromJSONTyped(json, false);
}

export function PublicInvoiceItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicInvoiceItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'costPerItem': json['costPerItem'],
        'totalCost': json['totalCost'],
        'name': json['name'],
        'title': json['title'],
        'description': json['description'],
        'amount': json['amount'],
    };
}

export function PublicInvoiceItemDtoToJSON(json: any): PublicInvoiceItemDto {
    return PublicInvoiceItemDtoToJSONTyped(json, false);
}

export function PublicInvoiceItemDtoToJSONTyped(value?: PublicInvoiceItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'costPerItem': value['costPerItem'],
        'totalCost': value['totalCost'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'amount': value['amount'],
    };
}

