/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPeriodStatus } from './SubscriptionPeriodStatus';
import {
    SubscriptionPeriodStatusFromJSON,
    SubscriptionPeriodStatusFromJSONTyped,
    SubscriptionPeriodStatusToJSON,
    SubscriptionPeriodStatusToJSONTyped,
} from './SubscriptionPeriodStatus';

/**
 * 
 * @export
 * @interface PublicSubscriptionPeriodDto
 */
export interface PublicSubscriptionPeriodDto {
    /**
     * 
     * @type {SubscriptionPeriodStatus}
     * @memberof PublicSubscriptionPeriodDto
     */
    status: SubscriptionPeriodStatus;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionPeriodDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicSubscriptionPeriodDto
     */
    startsAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PublicSubscriptionPeriodDto
     */
    endsAt: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicSubscriptionPeriodDto
     */
    offerId: string;
}



/**
 * Check if a given object implements the PublicSubscriptionPeriodDto interface.
 */
export function instanceOfPublicSubscriptionPeriodDto(value: object): value is PublicSubscriptionPeriodDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    if (!('offerId' in value) || value['offerId'] === undefined) return false;
    return true;
}

export function PublicSubscriptionPeriodDtoFromJSON(json: any): PublicSubscriptionPeriodDto {
    return PublicSubscriptionPeriodDtoFromJSONTyped(json, false);
}

export function PublicSubscriptionPeriodDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSubscriptionPeriodDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': SubscriptionPeriodStatusFromJSON(json['status']),
        'id': json['id'],
        'startsAt': (new Date(json['startsAt'])),
        'endsAt': (new Date(json['endsAt'])),
        'offerId': json['offerId'],
    };
}

export function PublicSubscriptionPeriodDtoToJSON(json: any): PublicSubscriptionPeriodDto {
    return PublicSubscriptionPeriodDtoToJSONTyped(json, false);
}

export function PublicSubscriptionPeriodDtoToJSONTyped(value?: PublicSubscriptionPeriodDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': SubscriptionPeriodStatusToJSON(value['status']),
        'id': value['id'],
        'startsAt': ((value['startsAt']).toISOString()),
        'endsAt': ((value['endsAt']).toISOString()),
        'offerId': value['offerId'],
    };
}

