/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicContentDto } from './PublicContentDto';
import {
    PublicContentDtoFromJSON,
    PublicContentDtoFromJSONTyped,
    PublicContentDtoToJSON,
    PublicContentDtoToJSONTyped,
} from './PublicContentDto';
import type { PublicPlanDto } from './PublicPlanDto';
import {
    PublicPlanDtoFromJSON,
    PublicPlanDtoFromJSONTyped,
    PublicPlanDtoToJSON,
    PublicPlanDtoToJSONTyped,
} from './PublicPlanDto';

/**
 * 
 * @export
 * @interface PublicOfferWithPlanDto
 */
export interface PublicOfferWithPlanDto {
    /**
     * 
     * @type {string}
     * @memberof PublicOfferWithPlanDto
     */
    cost: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferWithPlanDto
     */
    originalCost: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferWithPlanDto
     */
    providedCredits: string | null;
    /**
     * 
     * @type {PublicContentDto}
     * @memberof PublicOfferWithPlanDto
     */
    content: PublicContentDto;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferWithPlanDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferWithPlanDto
     */
    legalId: string;
    /**
     * 
     * @type {number}
     * @memberof PublicOfferWithPlanDto
     */
    sort: number;
    /**
     * 
     * @type {Date}
     * @memberof PublicOfferWithPlanDto
     */
    validFrom: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PublicOfferWithPlanDto
     */
    validUntil: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferWithPlanDto
     */
    planId: string;
    /**
     * 
     * @type {PublicPlanDto}
     * @memberof PublicOfferWithPlanDto
     */
    plan: PublicPlanDto;
}

/**
 * Check if a given object implements the PublicOfferWithPlanDto interface.
 */
export function instanceOfPublicOfferWithPlanDto(value: object): value is PublicOfferWithPlanDto {
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('originalCost' in value) || value['originalCost'] === undefined) return false;
    if (!('providedCredits' in value) || value['providedCredits'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('legalId' in value) || value['legalId'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
    if (!('validUntil' in value) || value['validUntil'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    return true;
}

export function PublicOfferWithPlanDtoFromJSON(json: any): PublicOfferWithPlanDto {
    return PublicOfferWithPlanDtoFromJSONTyped(json, false);
}

export function PublicOfferWithPlanDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOfferWithPlanDto {
    if (json == null) {
        return json;
    }
    return {
        
        'cost': json['cost'],
        'originalCost': json['originalCost'],
        'providedCredits': json['providedCredits'],
        'content': PublicContentDtoFromJSON(json['content']),
        'id': json['id'],
        'legalId': json['legalId'],
        'sort': json['sort'],
        'validFrom': (json['validFrom'] == null ? null : new Date(json['validFrom'])),
        'validUntil': (json['validUntil'] == null ? null : new Date(json['validUntil'])),
        'planId': json['planId'],
        'plan': PublicPlanDtoFromJSON(json['plan']),
    };
}

export function PublicOfferWithPlanDtoToJSON(json: any): PublicOfferWithPlanDto {
    return PublicOfferWithPlanDtoToJSONTyped(json, false);
}

export function PublicOfferWithPlanDtoToJSONTyped(value?: PublicOfferWithPlanDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cost': value['cost'],
        'originalCost': value['originalCost'],
        'providedCredits': value['providedCredits'],
        'content': PublicContentDtoToJSON(value['content']),
        'id': value['id'],
        'legalId': value['legalId'],
        'sort': value['sort'],
        'validFrom': (value['validFrom'] == null ? null : (value['validFrom'] as any).toISOString()),
        'validUntil': (value['validUntil'] == null ? null : (value['validUntil'] as any).toISOString()),
        'planId': value['planId'],
        'plan': PublicPlanDtoToJSON(value['plan']),
    };
}

