/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicCountryDto
 */
export interface PublicCountryDto {
    /**
     * 
     * @type {string}
     * @memberof PublicCountryDto
     */
    rate: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicCountryDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicCountryDto
     */
    favourite: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PublicCountryDto
     */
    roaming: boolean;
}

/**
 * Check if a given object implements the PublicCountryDto interface.
 */
export function instanceOfPublicCountryDto(value: object): value is PublicCountryDto {
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('favourite' in value) || value['favourite'] === undefined) return false;
    if (!('roaming' in value) || value['roaming'] === undefined) return false;
    return true;
}

export function PublicCountryDtoFromJSON(json: any): PublicCountryDto {
    return PublicCountryDtoFromJSONTyped(json, false);
}

export function PublicCountryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCountryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rate': json['rate'],
        'name': json['name'],
        'favourite': json['favourite'],
        'roaming': json['roaming'],
    };
}

export function PublicCountryDtoToJSON(json: any): PublicCountryDto {
    return PublicCountryDtoToJSONTyped(json, false);
}

export function PublicCountryDtoToJSONTyped(value?: PublicCountryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rate': value['rate'],
        'name': value['name'],
        'favourite': value['favourite'],
        'roaming': value['roaming'],
    };
}

