/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicSigningRequestDto
 */
export interface PublicSigningRequestDto {
    /**
     * 
     * @type {string}
     * @memberof PublicSigningRequestDto
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSigningRequestDto
     */
    message: string;
}

/**
 * Check if a given object implements the PublicSigningRequestDto interface.
 */
export function instanceOfPublicSigningRequestDto(value: object): value is PublicSigningRequestDto {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PublicSigningRequestDtoFromJSON(json: any): PublicSigningRequestDto {
    return PublicSigningRequestDtoFromJSONTyped(json, false);
}

export function PublicSigningRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSigningRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'message': json['message'],
    };
}

export function PublicSigningRequestDtoToJSON(json: any): PublicSigningRequestDto {
    return PublicSigningRequestDtoToJSONTyped(json, false);
}

export function PublicSigningRequestDtoToJSONTyped(value?: PublicSigningRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'message': value['message'],
    };
}

