/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicCertificateDto
 */
export interface PublicCertificateDto {
    /**
     * 
     * @type {string}
     * @memberof PublicCertificateDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCertificateDto
     */
    phoneNumberMsisdn: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicCertificateDto
     */
    issuedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PublicCertificateDto
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the PublicCertificateDto interface.
 */
export function instanceOfPublicCertificateDto(value: object): value is PublicCertificateDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('phoneNumberMsisdn' in value) || value['phoneNumberMsisdn'] === undefined) return false;
    if (!('issuedAt' in value) || value['issuedAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function PublicCertificateDtoFromJSON(json: any): PublicCertificateDto {
    return PublicCertificateDtoFromJSONTyped(json, false);
}

export function PublicCertificateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCertificateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'phoneNumberMsisdn': json['phoneNumberMsisdn'],
        'issuedAt': (new Date(json['issuedAt'])),
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function PublicCertificateDtoToJSON(json: any): PublicCertificateDto {
    return PublicCertificateDtoToJSONTyped(json, false);
}

export function PublicCertificateDtoToJSONTyped(value?: PublicCertificateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'phoneNumberMsisdn': value['phoneNumberMsisdn'],
        'issuedAt': ((value['issuedAt']).toISOString()),
        'expiresAt': ((value['expiresAt']).toISOString()),
    };
}

