/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicAuthAppleExchangeDto
 */
export interface PublicAuthAppleExchangeDto {
    /**
     * 
     * @type {string}
     * @memberof PublicAuthAppleExchangeDto
     */
    issuerUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthAppleExchangeDto
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthAppleExchangeDto
     */
    redirectUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthAppleExchangeDto
     */
    scope: string;
}

/**
 * Check if a given object implements the PublicAuthAppleExchangeDto interface.
 */
export function instanceOfPublicAuthAppleExchangeDto(value: object): value is PublicAuthAppleExchangeDto {
    if (!('issuerUrl' in value) || value['issuerUrl'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('redirectUrl' in value) || value['redirectUrl'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function PublicAuthAppleExchangeDtoFromJSON(json: any): PublicAuthAppleExchangeDto {
    return PublicAuthAppleExchangeDtoFromJSONTyped(json, false);
}

export function PublicAuthAppleExchangeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAuthAppleExchangeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'issuerUrl': json['issuerUrl'],
        'clientId': json['clientId'],
        'redirectUrl': json['redirectUrl'],
        'scope': json['scope'],
    };
}

export function PublicAuthAppleExchangeDtoToJSON(json: any): PublicAuthAppleExchangeDto {
    return PublicAuthAppleExchangeDtoToJSONTyped(json, false);
}

export function PublicAuthAppleExchangeDtoToJSONTyped(value?: PublicAuthAppleExchangeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuerUrl': value['issuerUrl'],
        'clientId': value['clientId'],
        'redirectUrl': value['redirectUrl'],
        'scope': value['scope'],
    };
}

