/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicTokenHistoryEntryDto
 */
export interface PublicTokenHistoryEntryDto {
    /**
     * 
     * @type {Date}
     * @memberof PublicTokenHistoryEntryDto
     */
    ts: Date;
    /**
     * 
     * @type {number}
     * @memberof PublicTokenHistoryEntryDto
     */
    price: number;
}

/**
 * Check if a given object implements the PublicTokenHistoryEntryDto interface.
 */
export function instanceOfPublicTokenHistoryEntryDto(value: object): value is PublicTokenHistoryEntryDto {
    if (!('ts' in value) || value['ts'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function PublicTokenHistoryEntryDtoFromJSON(json: any): PublicTokenHistoryEntryDto {
    return PublicTokenHistoryEntryDtoFromJSONTyped(json, false);
}

export function PublicTokenHistoryEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTokenHistoryEntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ts': (new Date(json['ts'])),
        'price': json['price'],
    };
}

export function PublicTokenHistoryEntryDtoToJSON(json: any): PublicTokenHistoryEntryDto {
    return PublicTokenHistoryEntryDtoToJSONTyped(json, false);
}

export function PublicTokenHistoryEntryDtoToJSONTyped(value?: PublicTokenHistoryEntryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ts': ((value['ts']).toISOString()),
        'price': value['price'],
    };
}

