/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicCoverageDto
 */
export interface PublicCoverageDto {
    /**
     * 
     * @type {number}
     * @memberof PublicCoverageDto
     */
    coverage: number | null;
}

/**
 * Check if a given object implements the PublicCoverageDto interface.
 */
export function instanceOfPublicCoverageDto(value: object): value is PublicCoverageDto {
    if (!('coverage' in value) || value['coverage'] === undefined) return false;
    return true;
}

export function PublicCoverageDtoFromJSON(json: any): PublicCoverageDto {
    return PublicCoverageDtoFromJSONTyped(json, false);
}

export function PublicCoverageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCoverageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'coverage': json['coverage'],
    };
}

export function PublicCoverageDtoToJSON(json: any): PublicCoverageDto {
    return PublicCoverageDtoToJSONTyped(json, false);
}

export function PublicCoverageDtoToJSONTyped(value?: PublicCoverageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coverage': value['coverage'],
    };
}

