/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnboardingStageType } from './OnboardingStageType';
import {
    OnboardingStageTypeFromJSON,
    OnboardingStageTypeFromJSONTyped,
    OnboardingStageTypeToJSON,
    OnboardingStageTypeToJSONTyped,
} from './OnboardingStageType';
import type { PublicContentDto } from './PublicContentDto';
import {
    PublicContentDtoFromJSON,
    PublicContentDtoFromJSONTyped,
    PublicContentDtoToJSON,
    PublicContentDtoToJSONTyped,
} from './PublicContentDto';
import type { PublicOnboardingStageDtoData } from './PublicOnboardingStageDtoData';
import {
    PublicOnboardingStageDtoDataFromJSON,
    PublicOnboardingStageDtoDataFromJSONTyped,
    PublicOnboardingStageDtoDataToJSON,
    PublicOnboardingStageDtoDataToJSONTyped,
} from './PublicOnboardingStageDtoData';

/**
 * 
 * @export
 * @interface PublicOnboardingStageDto
 */
export interface PublicOnboardingStageDto {
    /**
     * 
     * @type {OnboardingStageType}
     * @memberof PublicOnboardingStageDto
     */
    type: OnboardingStageType;
    /**
     * 
     * @type {PublicContentDto}
     * @memberof PublicOnboardingStageDto
     */
    content: PublicContentDto;
    /**
     * 
     * @type {PublicOnboardingStageDtoData}
     * @memberof PublicOnboardingStageDto
     */
    data: PublicOnboardingStageDtoData | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOnboardingStageDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PublicOnboardingStageDto
     */
    sort: number;
    /**
     * 
     * @type {boolean}
     * @memberof PublicOnboardingStageDto
     */
    required: boolean;
}



/**
 * Check if a given object implements the PublicOnboardingStageDto interface.
 */
export function instanceOfPublicOnboardingStageDto(value: object): value is PublicOnboardingStageDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    if (!('required' in value) || value['required'] === undefined) return false;
    return true;
}

export function PublicOnboardingStageDtoFromJSON(json: any): PublicOnboardingStageDto {
    return PublicOnboardingStageDtoFromJSONTyped(json, false);
}

export function PublicOnboardingStageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOnboardingStageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': OnboardingStageTypeFromJSON(json['type']),
        'content': PublicContentDtoFromJSON(json['content']),
        'data': PublicOnboardingStageDtoDataFromJSON(json['data']),
        'name': json['name'],
        'sort': json['sort'],
        'required': json['required'],
    };
}

export function PublicOnboardingStageDtoToJSON(json: any): PublicOnboardingStageDto {
    return PublicOnboardingStageDtoToJSONTyped(json, false);
}

export function PublicOnboardingStageDtoToJSONTyped(value?: PublicOnboardingStageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': OnboardingStageTypeToJSON(value['type']),
        'content': PublicContentDtoToJSON(value['content']),
        'data': PublicOnboardingStageDtoDataToJSON(value['data']),
        'name': value['name'],
        'sort': value['sort'],
        'required': value['required'],
    };
}

