/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshDto
 */
export interface RefreshDto {
    /**
     * 
     * @type {string}
     * @memberof RefreshDto
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the RefreshDto interface.
 */
export function instanceOfRefreshDto(value: object): value is RefreshDto {
    return true;
}

export function RefreshDtoFromJSON(json: any): RefreshDto {
    return RefreshDtoFromJSONTyped(json, false);
}

export function RefreshDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshDto {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function RefreshDtoToJSON(json: any): RefreshDto {
    return RefreshDtoToJSONTyped(json, false);
}

export function RefreshDtoToJSONTyped(value?: RefreshDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

