/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetVerifyDto
 */
export interface ResetVerifyDto {
    /**
     * 
     * @type {string}
     * @memberof ResetVerifyDto
     */
    email: string;
}

/**
 * Check if a given object implements the ResetVerifyDto interface.
 */
export function instanceOfResetVerifyDto(value: object): value is ResetVerifyDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResetVerifyDtoFromJSON(json: any): ResetVerifyDto {
    return ResetVerifyDtoFromJSONTyped(json, false);
}

export function ResetVerifyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetVerifyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResetVerifyDtoToJSON(json: any): ResetVerifyDto {
    return ResetVerifyDtoToJSONTyped(json, false);
}

export function ResetVerifyDtoToJSONTyped(value?: ResetVerifyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

