/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPasswordDto
 */
export interface SetPasswordDto {
    /**
     * 
     * @type {string}
     * @memberof SetPasswordDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SetPasswordDto
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof SetPasswordDto
     */
    password: string;
}

/**
 * Check if a given object implements the SetPasswordDto interface.
 */
export function instanceOfSetPasswordDto(value: object): value is SetPasswordDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SetPasswordDtoFromJSON(json: any): SetPasswordDto {
    return SetPasswordDtoFromJSONTyped(json, false);
}

export function SetPasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
        'password': json['password'],
    };
}

export function SetPasswordDtoToJSON(json: any): SetPasswordDto {
    return SetPasswordDtoToJSONTyped(json, false);
}

export function SetPasswordDtoToJSONTyped(value?: SetPasswordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'code': value['code'],
        'password': value['password'],
    };
}

