/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupDto
 */
export interface SignupDto {
    /**
     * 
     * @type {string}
     * @memberof SignupDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof SignupDto
     */
    lastName: string;
}

/**
 * Check if a given object implements the SignupDto interface.
 */
export function instanceOfSignupDto(value: object): value is SignupDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function SignupDtoFromJSON(json: any): SignupDto {
    return SignupDtoFromJSONTyped(json, false);
}

export function SignupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function SignupDtoToJSON(json: any): SignupDto {
    return SignupDtoToJSONTyped(json, false);
}

export function SignupDtoToJSONTyped(value?: SignupDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

