/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimType } from './SimType';
import {
    SimTypeFromJSON,
    SimTypeFromJSONTyped,
    SimTypeToJSON,
    SimTypeToJSONTyped,
} from './SimType';

/**
 * 
 * @export
 * @interface SimSelectionDto
 */
export interface SimSelectionDto {
    /**
     * 
     * @type {SimType}
     * @memberof SimSelectionDto
     */
    simType: SimType;
    /**
     * 
     * @type {string}
     * @memberof SimSelectionDto
     */
    iccid?: string;
}



/**
 * Check if a given object implements the SimSelectionDto interface.
 */
export function instanceOfSimSelectionDto(value: object): value is SimSelectionDto {
    if (!('simType' in value) || value['simType'] === undefined) return false;
    return true;
}

export function SimSelectionDtoFromJSON(json: any): SimSelectionDto {
    return SimSelectionDtoFromJSONTyped(json, false);
}

export function SimSelectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimSelectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'simType': SimTypeFromJSON(json['simType']),
        'iccid': json['iccid'] == null ? undefined : json['iccid'],
    };
}

export function SimSelectionDtoToJSON(json: any): SimSelectionDto {
    return SimSelectionDtoToJSONTyped(json, false);
}

export function SimSelectionDtoToJSONTyped(value?: SimSelectionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simType': SimTypeToJSON(value['simType']),
        'iccid': value['iccid'],
    };
}

