/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SimType = {
    PSim: 'P_SIM',
    ESim: 'E_SIM'
} as const;
export type SimType = typeof SimType[keyof typeof SimType];


export function instanceOfSimType(value: any): boolean {
    for (const key in SimType) {
        if (Object.prototype.hasOwnProperty.call(SimType, key)) {
            if (SimType[key as keyof typeof SimType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SimTypeFromJSON(json: any): SimType {
    return SimTypeFromJSONTyped(json, false);
}

export function SimTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimType {
    return json as SimType;
}

export function SimTypeToJSON(value?: SimType | null): any {
    return value as any;
}

export function SimTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SimType {
    return value as SimType;
}

