/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SubscriptionPeriodStatus = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Done: 'DONE',
    Cancelled: 'CANCELLED',
    Failed: 'FAILED'
} as const;
export type SubscriptionPeriodStatus = typeof SubscriptionPeriodStatus[keyof typeof SubscriptionPeriodStatus];


export function instanceOfSubscriptionPeriodStatus(value: any): boolean {
    for (const key in SubscriptionPeriodStatus) {
        if (Object.prototype.hasOwnProperty.call(SubscriptionPeriodStatus, key)) {
            if (SubscriptionPeriodStatus[key as keyof typeof SubscriptionPeriodStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubscriptionPeriodStatusFromJSON(json: any): SubscriptionPeriodStatus {
    return SubscriptionPeriodStatusFromJSONTyped(json, false);
}

export function SubscriptionPeriodStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPeriodStatus {
    return json as SubscriptionPeriodStatus;
}

export function SubscriptionPeriodStatusToJSON(value?: SubscriptionPeriodStatus | null): any {
    return value as any;
}

export function SubscriptionPeriodStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): SubscriptionPeriodStatus {
    return value as SubscriptionPeriodStatus;
}

