/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyOnboardingProgressDto
 */
export interface UpdateMyOnboardingProgressDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOnboardingProgressDto
     */
    stage: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMyOnboardingProgressDto
     */
    completed: boolean;
}

/**
 * Check if a given object implements the UpdateMyOnboardingProgressDto interface.
 */
export function instanceOfUpdateMyOnboardingProgressDto(value: object): value is UpdateMyOnboardingProgressDto {
    if (!('stage' in value) || value['stage'] === undefined) return false;
    if (!('completed' in value) || value['completed'] === undefined) return false;
    return true;
}

export function UpdateMyOnboardingProgressDtoFromJSON(json: any): UpdateMyOnboardingProgressDto {
    return UpdateMyOnboardingProgressDtoFromJSONTyped(json, false);
}

export function UpdateMyOnboardingProgressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyOnboardingProgressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'stage': json['stage'],
        'completed': json['completed'],
    };
}

export function UpdateMyOnboardingProgressDtoToJSON(json: any): UpdateMyOnboardingProgressDto {
    return UpdateMyOnboardingProgressDtoToJSONTyped(json, false);
}

export function UpdateMyOnboardingProgressDtoToJSONTyped(value?: UpdateMyOnboardingProgressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stage': value['stage'],
        'completed': value['completed'],
    };
}

