/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimType } from './SimType';
import {
    SimTypeFromJSON,
    SimTypeFromJSONTyped,
    SimTypeToJSON,
    SimTypeToJSONTyped,
} from './SimType';

/**
 * 
 * @export
 * @interface UpdateMyOrderDto
 */
export interface UpdateMyOrderDto {
    /**
     * 
     * @type {SimType}
     * @memberof UpdateMyOrderDto
     */
    simType?: SimType;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderDto
     */
    offerId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMyOrderDto
     */
    isPortingIn?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderDto
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderDto
     */
    msisdn?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderDto
     */
    ospAccountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderDto
     */
    ospPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderDto
     */
    simIccid?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMyOrderDto
     */
    confirm?: boolean;
}



/**
 * Check if a given object implements the UpdateMyOrderDto interface.
 */
export function instanceOfUpdateMyOrderDto(value: object): value is UpdateMyOrderDto {
    return true;
}

export function UpdateMyOrderDtoFromJSON(json: any): UpdateMyOrderDto {
    return UpdateMyOrderDtoFromJSONTyped(json, false);
}

export function UpdateMyOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyOrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'simType': json['simType'] == null ? undefined : SimTypeFromJSON(json['simType']),
        'offerId': json['offerId'] == null ? undefined : json['offerId'],
        'isPortingIn': json['isPortingIn'] == null ? undefined : json['isPortingIn'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'msisdn': json['msisdn'] == null ? undefined : json['msisdn'],
        'ospAccountNumber': json['ospAccountNumber'] == null ? undefined : json['ospAccountNumber'],
        'ospPassword': json['ospPassword'] == null ? undefined : json['ospPassword'],
        'simIccid': json['simIccid'] == null ? undefined : json['simIccid'],
        'confirm': json['confirm'] == null ? undefined : json['confirm'],
    };
}

export function UpdateMyOrderDtoToJSON(json: any): UpdateMyOrderDto {
    return UpdateMyOrderDtoToJSONTyped(json, false);
}

export function UpdateMyOrderDtoToJSONTyped(value?: UpdateMyOrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simType': SimTypeToJSON(value['simType']),
        'offerId': value['offerId'],
        'isPortingIn': value['isPortingIn'],
        'postalCode': value['postalCode'],
        'msisdn': value['msisdn'],
        'ospAccountNumber': value['ospAccountNumber'],
        'ospPassword': value['ospPassword'],
        'simIccid': value['simIccid'],
        'confirm': value['confirm'],
    };
}

