/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletCashbackCurrency } from './WalletCashbackCurrency';
import {
    WalletCashbackCurrencyFromJSON,
    WalletCashbackCurrencyFromJSONTyped,
    WalletCashbackCurrencyToJSON,
    WalletCashbackCurrencyToJSONTyped,
} from './WalletCashbackCurrency';

/**
 * 
 * @export
 * @interface UpdateUserSettingsDto
 */
export interface UpdateUserSettingsDto {
    /**
     * 
     * @type {WalletCashbackCurrency}
     * @memberof UpdateUserSettingsDto
     */
    cashbackCurrency?: WalletCashbackCurrency;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserSettingsDto
     */
    email?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserSettingsDto
     */
    mail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserSettingsDto
     */
    sms?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserSettingsDto
     */
    cpni?: boolean;
}



/**
 * Check if a given object implements the UpdateUserSettingsDto interface.
 */
export function instanceOfUpdateUserSettingsDto(value: object): value is UpdateUserSettingsDto {
    return true;
}

export function UpdateUserSettingsDtoFromJSON(json: any): UpdateUserSettingsDto {
    return UpdateUserSettingsDtoFromJSONTyped(json, false);
}

export function UpdateUserSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'cashbackCurrency': json['cashbackCurrency'] == null ? undefined : WalletCashbackCurrencyFromJSON(json['cashbackCurrency']),
        'email': json['email'] == null ? undefined : json['email'],
        'mail': json['mail'] == null ? undefined : json['mail'],
        'sms': json['sms'] == null ? undefined : json['sms'],
        'cpni': json['cpni'] == null ? undefined : json['cpni'],
    };
}

export function UpdateUserSettingsDtoToJSON(json: any): UpdateUserSettingsDto {
    return UpdateUserSettingsDtoToJSONTyped(json, false);
}

export function UpdateUserSettingsDtoToJSONTyped(value?: UpdateUserSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cashbackCurrency': WalletCashbackCurrencyToJSON(value['cashbackCurrency']),
        'email': value['email'],
        'mail': value['mail'],
        'sms': value['sms'],
        'cpni': value['cpni'],
    };
}

