/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortInDto } from './PortInDto';
import {
    PortInDtoFromJSON,
    PortInDtoFromJSONTyped,
    PortInDtoToJSON,
    PortInDtoToJSONTyped,
} from './PortInDto';
import type { SimSelectionDto } from './SimSelectionDto';
import {
    SimSelectionDtoFromJSON,
    SimSelectionDtoFromJSONTyped,
    SimSelectionDtoToJSON,
    SimSelectionDtoToJSONTyped,
} from './SimSelectionDto';

/**
 * 
 * @export
 * @interface UpdateMyOrderV2Dto
 */
export interface UpdateMyOrderV2Dto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderV2Dto
     */
    offerId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderV2Dto
     */
    promoCodeId?: string;
    /**
     * 
     * @type {PortInDto}
     * @memberof UpdateMyOrderV2Dto
     */
    portIn?: PortInDto;
    /**
     * 
     * @type {SimSelectionDto}
     * @memberof UpdateMyOrderV2Dto
     */
    simSelection?: SimSelectionDto;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMyOrderV2Dto
     */
    confirm?: boolean;
}

/**
 * Check if a given object implements the UpdateMyOrderV2Dto interface.
 */
export function instanceOfUpdateMyOrderV2Dto(value: object): value is UpdateMyOrderV2Dto {
    return true;
}

export function UpdateMyOrderV2DtoFromJSON(json: any): UpdateMyOrderV2Dto {
    return UpdateMyOrderV2DtoFromJSONTyped(json, false);
}

export function UpdateMyOrderV2DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyOrderV2Dto {
    if (json == null) {
        return json;
    }
    return {
        
        'offerId': json['offerId'] == null ? undefined : json['offerId'],
        'promoCodeId': json['promoCodeId'] == null ? undefined : json['promoCodeId'],
        'portIn': json['portIn'] == null ? undefined : PortInDtoFromJSON(json['portIn']),
        'simSelection': json['simSelection'] == null ? undefined : SimSelectionDtoFromJSON(json['simSelection']),
        'confirm': json['confirm'] == null ? undefined : json['confirm'],
    };
}

export function UpdateMyOrderV2DtoToJSON(json: any): UpdateMyOrderV2Dto {
    return UpdateMyOrderV2DtoToJSONTyped(json, false);
}

export function UpdateMyOrderV2DtoToJSONTyped(value?: UpdateMyOrderV2Dto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offerId': value['offerId'],
        'promoCodeId': value['promoCodeId'],
        'portIn': PortInDtoToJSON(value['portIn']),
        'simSelection': SimSelectionDtoToJSON(value['simSelection']),
        'confirm': value['confirm'],
    };
}

