/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyWalletDto
 */
export interface UpdateMyWalletDto {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMyWalletDto
     */
    cloudBackup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMyWalletDto
     */
    localBackup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMyWalletDto
     */
    readOnly?: boolean;
}

/**
 * Check if a given object implements the UpdateMyWalletDto interface.
 */
export function instanceOfUpdateMyWalletDto(value: object): value is UpdateMyWalletDto {
    return true;
}

export function UpdateMyWalletDtoFromJSON(json: any): UpdateMyWalletDto {
    return UpdateMyWalletDtoFromJSONTyped(json, false);
}

export function UpdateMyWalletDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyWalletDto {
    if (json == null) {
        return json;
    }
    return {
        
        'cloudBackup': json['cloudBackup'] == null ? undefined : json['cloudBackup'],
        'localBackup': json['localBackup'] == null ? undefined : json['localBackup'],
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
    };
}

export function UpdateMyWalletDtoToJSON(json: any): UpdateMyWalletDto {
    return UpdateMyWalletDtoToJSONTyped(json, false);
}

export function UpdateMyWalletDtoToJSONTyped(value?: UpdateMyWalletDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cloudBackup': value['cloudBackup'],
        'localBackup': value['localBackup'],
        'readOnly': value['readOnly'],
    };
}

