/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMySubscriptionDto
 */
export interface UpdateMySubscriptionDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMySubscriptionDto
     */
    label?: string;
}

/**
 * Check if a given object implements the UpdateMySubscriptionDto interface.
 */
export function instanceOfUpdateMySubscriptionDto(value: object): value is UpdateMySubscriptionDto {
    return true;
}

export function UpdateMySubscriptionDtoFromJSON(json: any): UpdateMySubscriptionDto {
    return UpdateMySubscriptionDtoFromJSONTyped(json, false);
}

export function UpdateMySubscriptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMySubscriptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function UpdateMySubscriptionDtoToJSON(json: any): UpdateMySubscriptionDto {
    return UpdateMySubscriptionDtoToJSONTyped(json, false);
}

export function UpdateMySubscriptionDtoToJSONTyped(value?: UpdateMySubscriptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
    };
}

