/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateUserSettingsDto } from './UpdateUserSettingsDto';
import {
    UpdateUserSettingsDtoFromJSON,
    UpdateUserSettingsDtoFromJSONTyped,
    UpdateUserSettingsDtoToJSON,
    UpdateUserSettingsDtoToJSONTyped,
} from './UpdateUserSettingsDto';

/**
 * 
 * @export
 * @interface UpdateMeDto
 */
export interface UpdateMeDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMeDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMeDto
     */
    lastName?: string;
    /**
     * 
     * @type {UpdateUserSettingsDto}
     * @memberof UpdateMeDto
     */
    settings?: UpdateUserSettingsDto;
}

/**
 * Check if a given object implements the UpdateMeDto interface.
 */
export function instanceOfUpdateMeDto(value: object): value is UpdateMeDto {
    return true;
}

export function UpdateMeDtoFromJSON(json: any): UpdateMeDto {
    return UpdateMeDtoFromJSONTyped(json, false);
}

export function UpdateMeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'settings': json['settings'] == null ? undefined : UpdateUserSettingsDtoFromJSON(json['settings']),
    };
}

export function UpdateMeDtoToJSON(json: any): UpdateMeDto {
    return UpdateMeDtoToJSONTyped(json, false);
}

export function UpdateMeDtoToJSONTyped(value?: UpdateMeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'settings': UpdateUserSettingsDtoToJSON(value['settings']),
    };
}

