/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyOrderStepSignDto
 */
export interface UpdateMyOrderStepSignDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderStepSignDto
     */
    signature: string;
}

/**
 * Check if a given object implements the UpdateMyOrderStepSignDto interface.
 */
export function instanceOfUpdateMyOrderStepSignDto(value: object): value is UpdateMyOrderStepSignDto {
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function UpdateMyOrderStepSignDtoFromJSON(json: any): UpdateMyOrderStepSignDto {
    return UpdateMyOrderStepSignDtoFromJSONTyped(json, false);
}

export function UpdateMyOrderStepSignDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyOrderStepSignDto {
    if (json == null) {
        return json;
    }
    return {
        
        'signature': json['signature'],
    };
}

export function UpdateMyOrderStepSignDtoToJSON(json: any): UpdateMyOrderStepSignDto {
    return UpdateMyOrderStepSignDtoToJSONTyped(json, false);
}

export function UpdateMyOrderStepSignDtoToJSONTyped(value?: UpdateMyOrderStepSignDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signature': value['signature'],
    };
}

