/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyOrderStepAttachSimDto
 */
export interface UpdateMyOrderStepAttachSimDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMyOrderStepAttachSimDto
     */
    iccid: string;
}

/**
 * Check if a given object implements the UpdateMyOrderStepAttachSimDto interface.
 */
export function instanceOfUpdateMyOrderStepAttachSimDto(value: object): value is UpdateMyOrderStepAttachSimDto {
    if (!('iccid' in value) || value['iccid'] === undefined) return false;
    return true;
}

export function UpdateMyOrderStepAttachSimDtoFromJSON(json: any): UpdateMyOrderStepAttachSimDto {
    return UpdateMyOrderStepAttachSimDtoFromJSONTyped(json, false);
}

export function UpdateMyOrderStepAttachSimDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyOrderStepAttachSimDto {
    if (json == null) {
        return json;
    }
    return {
        
        'iccid': json['iccid'],
    };
}

export function UpdateMyOrderStepAttachSimDtoToJSON(json: any): UpdateMyOrderStepAttachSimDto {
    return UpdateMyOrderStepAttachSimDtoToJSONTyped(json, false);
}

export function UpdateMyOrderStepAttachSimDtoToJSONTyped(value?: UpdateMyOrderStepAttachSimDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iccid': value['iccid'],
    };
}

