/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateMyWalletDto
 */
export interface ValidateMyWalletDto {
    /**
     * 
     * @type {string}
     * @memberof ValidateMyWalletDto
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateMyWalletDto
     */
    signature: string;
}

/**
 * Check if a given object implements the ValidateMyWalletDto interface.
 */
export function instanceOfValidateMyWalletDto(value: object): value is ValidateMyWalletDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function ValidateMyWalletDtoFromJSON(json: any): ValidateMyWalletDto {
    return ValidateMyWalletDtoFromJSONTyped(json, false);
}

export function ValidateMyWalletDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateMyWalletDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'signature': json['signature'],
    };
}

export function ValidateMyWalletDtoToJSON(json: any): ValidateMyWalletDto {
    return ValidateMyWalletDtoToJSONTyped(json, false);
}

export function ValidateMyWalletDtoToJSONTyped(value?: ValidateMyWalletDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'signature': value['signature'],
    };
}

