/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyDto
 */
export interface VerifyDto {
    /**
     * 
     * @type {string}
     * @memberof VerifyDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyDto
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyDto interface.
 */
export function instanceOfVerifyDto(value: object): value is VerifyDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyDtoFromJSON(json: any): VerifyDto {
    return VerifyDtoFromJSONTyped(json, false);
}

export function VerifyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function VerifyDtoToJSON(json: any): VerifyDto {
    return VerifyDtoToJSONTyped(json, false);
}

export function VerifyDtoToJSONTyped(value?: VerifyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

