/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VolumeType = {
    Data: 'DATA',
    Text: 'TEXT',
    Call: 'CALL',
    Credit: 'CREDIT'
} as const;
export type VolumeType = typeof VolumeType[keyof typeof VolumeType];


export function instanceOfVolumeType(value: any): boolean {
    for (const key in VolumeType) {
        if (Object.prototype.hasOwnProperty.call(VolumeType, key)) {
            if (VolumeType[key as keyof typeof VolumeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VolumeTypeFromJSON(json: any): VolumeType {
    return VolumeTypeFromJSONTyped(json, false);
}

export function VolumeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeType {
    return json as VolumeType;
}

export function VolumeTypeToJSON(value?: VolumeType | null): any {
    return value as any;
}

export function VolumeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): VolumeType {
    return value as VolumeType;
}

