/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WalletCashbackCurrency = {
    Sol: 'SOL',
    Usdc: 'USDC',
    Wbtc: 'WBTC'
} as const;
export type WalletCashbackCurrency = typeof WalletCashbackCurrency[keyof typeof WalletCashbackCurrency];


export function instanceOfWalletCashbackCurrency(value: any): boolean {
    for (const key in WalletCashbackCurrency) {
        if (Object.prototype.hasOwnProperty.call(WalletCashbackCurrency, key)) {
            if (WalletCashbackCurrency[key as keyof typeof WalletCashbackCurrency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WalletCashbackCurrencyFromJSON(json: any): WalletCashbackCurrency {
    return WalletCashbackCurrencyFromJSONTyped(json, false);
}

export function WalletCashbackCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletCashbackCurrency {
    return json as WalletCashbackCurrency;
}

export function WalletCashbackCurrencyToJSON(value?: WalletCashbackCurrency | null): any {
    return value as any;
}

export function WalletCashbackCurrencyToJSONTyped(value: any, ignoreDiscriminator: boolean): WalletCashbackCurrency {
    return value as WalletCashbackCurrency;
}

