/* tslint:disable */
/* eslint-disable */
/**
 * Fliggs
 * This is our cool new API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WalletProvider = {
    Solana: 'SOLANA'
} as const;
export type WalletProvider = typeof WalletProvider[keyof typeof WalletProvider];


export function instanceOfWalletProvider(value: any): boolean {
    for (const key in WalletProvider) {
        if (Object.prototype.hasOwnProperty.call(WalletProvider, key)) {
            if (WalletProvider[key as keyof typeof WalletProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WalletProviderFromJSON(json: any): WalletProvider {
    return WalletProviderFromJSONTyped(json, false);
}

export function WalletProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletProvider {
    return json as WalletProvider;
}

export function WalletProviderToJSON(value?: WalletProvider | null): any {
    return value as any;
}

export function WalletProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): WalletProvider {
    return value as WalletProvider;
}

